---
- id: ossindex:nuget:python2x86:303843
  title: "[CVE-2002-1119] os.&#95;execvpe from os.py in Python 2.2.1 and earlier creates
    temporary files with ..."
  description: os._execvpe from os.py in Python 2.2.1 and earlier creates temporary
    files with predictable names, which could allow local users to execute arbitrary
    code via a symlink attack.
  affected_package: python2x86
  vulnerable_versions:
  - 2.2.1
  package_manager: nuget
  cve:
  - CVE-2002-1119
  disclosed_date: 2002-10-04
  created_date: 2002-10-04
  last_modified_date: 2017-04-19
  credit:
  - OSSIndex
  references:
  - ftp://ftp.caldera.com/pub/security/OpenLinux/CSSA-2002-045.0.txt
  - http://distro.conectiva.com.br/atualizacoes/?id=a&anuncio=000527
  - http://mail.python.org/pipermail/python-dev/2002-August/027229.html
  - http://marc.info/?l=bugtraq&m=104333092200589&w=2
  - http://marc.theaimsgroup.com/?l=bugtraq&m=104333092200589&w=2
  - http://www.debian.org/security/2002/dsa-159
  - http://www.iss.net/security_center/static/10009.php
  - http://www.linux-mandrake.com/en/security/2002/MDKSA-2002-082.php
  - http://www.redhat.com/support/errata/RHSA-2002-202.html
  - http://www.redhat.com/support/errata/RHSA-2003-048.html
  - http://www.securityfocus.com/bid/5581
  source_url: https://ossindex.net/resource/package/8399917114/vulnerabilities
- id: ossindex:nuget:python2x86:306762
  title: "[CVE-2004-0150] Buffer overflow in the getaddrinfo function in Python 2.2
    before 2.2.2, when IPv..."
  description: Buffer overflow in the getaddrinfo function in Python 2.2 before 2.2.2,
    when IPv6 support is disabled, allows remote attackers to execute arbitrary code
    via an IPv6 address that is obtained using DNS.
  affected_package: python2x86
  vulnerable_versions:
  - '2.2'
  - 2.2.1
  package_manager: nuget
  cve:
  - CVE-2004-0150
  disclosed_date: 2004-04-15
  created_date: 2004-04-15
  last_modified_date: 2017-04-19
  credit:
  - OSSIndex
  references:
  - http://www.debian.org/security/2004/dsa-458
  - http://www.gentoo.org/security/en/glsa/glsa-200409-03.xml
  - http://www.mandrakesoft.com/security/advisories?name=MDKSA-2004:019
  - http://www.osvdb.org/4172
  - http://www.securityfocus.com/bid/9836
  - http://xforce.iss.net/xforce/xfdb/15409
  - https://exchange.xforce.ibmcloud.com/vulnerabilities/15409
  source_url: https://ossindex.net/resource/package/8399917114/vulnerabilities
- id: ossindex:nuget:python2x86:309380
  title: "[CVE-2005-0089] The SimpleXMLRPCServer library module in Python 2.2, 2.3
    before 2.3.5, and 2.4, ..."
  description: The SimpleXMLRPCServer library module in Python 2.2, 2.3 before 2.3.5,
    and 2.4, when used by XML-RPC servers that use the register_instance method to
    register an object without a _dispatch method, allows remote attackers to read
    or modify globals of the associated module, and possibly execute arbitrary code,
    via dotted attributes.
  affected_package: python2x86
  vulnerable_versions:
  - '2.2'
  - '2.3'
  - 2.3.1
  - 2.3.2
  - 2.3.3
  - 2.3.4
  - '2.4'
  package_manager: nuget
  cve:
  - CVE-2005-0089
  disclosed_date: 2005-05-02
  created_date: 2005-05-02
  last_modified_date: 2017-04-19
  credit:
  - OSSIndex
  references:
  - http://marc.info/?l=bugtraq&m=110746469728728&w=2
  - http://marc.theaimsgroup.com/?l=bugtraq&m=110746469728728&w=2
  - http://python.org/security/PSF-2005-001/patch-2.2.txt
  - http://secunia.com/advisories/14128
  - http://securitytracker.com/id?1013083
  - http://www.debian.org/security/2005/dsa-666
  - http://www.mandriva.com/security/advisories?name=MDKSA-2005:035
  - http://www.python.org/security/PSF-2005-001/
  - http://www.redhat.com/support/errata/RHSA-2005-108.html
  - http://www.securityfocus.com/bid/12437
  - http://www.trustix.org/errata/2005/0003/
  - http://xforce.iss.net/xforce/xfdb/19217
  - https://exchange.xforce.ibmcloud.com/vulnerabilities/19217
  source_url: https://ossindex.net/resource/package/8399917114/vulnerabilities
- id: ossindex:nuget:python2x86:315493
  title: "[CVE-2006-1542] Stack-based buffer overflow in Python 2.4.2 and earlier,
    running on Linux 2.6.12..."
  description: 'Stack-based buffer overflow in Python 2.4.2 and earlier, running on
    Linux 2.6.12.5 under gcc 4.0.3 with libc 2.3.5, allows local users to cause a
    "stack overflow," and possibly gain privileges, by running a script from a current
    working directory that has a long name, related to the realpath function.  NOTE:
    this might not be a vulnerability. However, the fact that it appears in a programming
    language interpreter could mean that some applications are affected, although
    attack scenarios might be limited because the attacker might already need to cross
    privilege boundaries to cause an exploitable program to be placed in a directory
    with a long name; or, depending on the method that Python uses to determine the
    current working directory, setuid applications might be affected.'
  affected_package: python2x86
  vulnerable_versions:
  - '2.2'
  - 2.2.1
  - '2.3'
  - 2.3.1
  - 2.3.2
  - 2.3.3
  - 2.3.4
  - '2.4'
  - 2.4.2
  package_manager: nuget
  cve:
  - CVE-2006-1542
  disclosed_date: 2006-03-30
  created_date: 2006-03-30
  last_modified_date: 2017-04-19
  credit:
  - OSSIndex
  references:
  - http://milw0rm.com/exploits/1591
  - http://secunia.com/advisories/31492
  - http://www.gotfault.net/research/exploit/gexp-python.py
  - http://www.redhat.com/support/errata/RHSA-2008-0629.html
  - https://www.exploit-db.com/exploits/1591
  source_url: https://ossindex.net/resource/package/8399917114/vulnerabilities
- id: ossindex:nuget:python2x86:318831
  title: "[CVE-2006-4980] Buffer overflow in the repr function in Python 2.3 through
    2.6 before 20060822 a..."
  description: Buffer overflow in the repr function in Python 2.3 through 2.6 before
    20060822 allows context-dependent attackers to cause a denial of service and possibly
    execute arbitrary code via crafted wide character UTF-32/UCS-4 strings to certain
    scripts.
  affected_package: python2x86
  vulnerable_versions:
  - '2.3'
  - 2.3.1
  - 2.3.2
  - 2.3.3
  - 2.3.4
  - 2.3.5
  - '2.4'
  - 2.4.2
  - 2.4.3
  - 2.5_alpha_1
  - 2.5_alpha_2
  - 2.5_beta_1
  - 2.5_beta_2
  - 2.5_beta_3
  - 2.5_final
  - 2.5_release_candidate_1
  - 2.5_release_candidate_2
  package_manager: nuget
  cve:
  - CVE-2006-4980
  disclosed_date: 2006-10-10
  created_date: 2006-10-10
  last_modified_date: 2017-07-20
  credit:
  - OSSIndex
  references:
  - ftp://patches.sgi.com/support/free/security/advisories/20061001-01-P.asc
  - http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=391589
  - http://bugzilla.redhat.com/bugzilla/show_bug.cgi?id=208162
  - http://kb.vmware.com/KanisaPlatform/Publishing/882/5120103_f.SAL_Public.html
  - http://secunia.com/advisories/22276
  - http://secunia.com/advisories/22297
  - http://secunia.com/advisories/22303
  - http://secunia.com/advisories/22357
  - http://secunia.com/advisories/22358
  - http://secunia.com/advisories/22379
  - http://secunia.com/advisories/22448
  - http://secunia.com/advisories/22487
  - http://secunia.com/advisories/22512
  - http://secunia.com/advisories/22531
  - http://secunia.com/advisories/22639
  - http://secunia.com/advisories/23680
  - http://secunia.com/advisories/31492
  - http://security.gentoo.org/glsa/glsa-200610-07.xml
  - http://securitytracker.com/id?1017019
  - http://sourceforge.net/tracker/index.php?func=detail&aid=1541585&group_id=5470&atid=305470
  - http://support.avaya.com/elmodocs2/security/ASA-2006-229.htm
  - http://www.debian.org/security/2006/dsa-1197
  - http://www.debian.org/security/2006/dsa-1198
  - http://www.mandriva.com/security/advisories?name=MDKSA-2006:181
  - http://www.novell.com/linux/security/advisories/2006_25_sr.html
  - http://www.redhat.com/support/errata/RHSA-2006-0713.html
  - http://www.redhat.com/support/errata/RHSA-2008-0629.html
  - http://www.securityfocus.com/archive/1/archive/1/448244/100/100/threaded
  - http://www.securityfocus.com/archive/1/archive/1/456546/100/200/threaded
  - http://www.securityfocus.com/bid/20376
  - http://www.ubuntu.com/usn/usn-359-1
  - http://www.vmware.com/support/vi3/doc/esx-3069097-patch.html
  - http://www.vmware.com/support/vi3/doc/esx-9986131-patch.html
  - http://www.vupen.com/english/advisories/2006/3940
  - http://www.vupen.com/english/advisories/2006/5131
  - http://xforce.iss.net/xforce/xfdb/29408
  - http://zoehep.xent.com/~bsittler/python2.4-2.4.3_unicodeobject.c.diff
  - https://exchange.xforce.ibmcloud.com/vulnerabilities/29408
  - https://issues.rpath.com/browse/RPL-702
  - https://launchpad.net/distros/ubuntu/%20source/python2.4/%20bug/56633
  - https://launchpad.net/distros/ubuntu/+source/python2.4/+bug/56633
  source_url: https://ossindex.net/resource/package/8399917114/vulnerabilities
- id: ossindex:nuget:python2x86:322640
  title: "[CVE-2007-1657] Stack-based buffer overflow in the file&#95;compress function
    in minigzip (Modules/z..."
  description: Stack-based buffer overflow in the file_compress function in minigzip
    (Modules/zlib) in Python 2.5 allows context-dependent attackers to execute arbitrary
    code via a long file argument.
  affected_package: python2x86
  vulnerable_versions:
  - '2.5'
  package_manager: nuget
  cve:
  - CVE-2007-1657
  disclosed_date: 2007-03-24
  created_date: 2007-03-24
  last_modified_date: 2017-04-19
  credit:
  - OSSIndex
  references:
  - http://attrition.org/pipermail/vim/2007-March/001430.html
  - http://osvdb.org/43550
  - http://www.securityfocus.com/archive/1/archive/1/462799/100/0/threaded
  - http://www.securityfocus.com/bid/22964
  source_url: https://ossindex.net/resource/package/8399917114/vulnerabilities
- id: ossindex:nuget:python2x86:323021
  title: "[CVE-2007-2052]  Numeric Errors"
  description: Off-by-one error in the PyLocale_strxfrm function in Modules/_localemodule.c
    for Python 2.4 and 2.5 causes an incorrect buffer size to be used for the strxfrm
    function, which allows context-dependent attackers to read portions of memory
    via unknown manipulations that trigger a buffer over-read due to missing null
    termination.
  affected_package: python2x86
  vulnerable_versions:
  - '2.4'
  - '2.5'
  package_manager: nuget
  cve:
  - CVE-2007-2052
  disclosed_date: 2007-04-16
  created_date: 2007-04-16
  last_modified_date: 2017-04-19
  credit:
  - OSSIndex
  references:
  - http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=416934
  - http://lists.vmware.com/pipermail/security-announce/2008/000005.html
  - http://secunia.com/advisories/25190
  - http://secunia.com/advisories/25217
  - http://secunia.com/advisories/25233
  - http://secunia.com/advisories/25353
  - http://secunia.com/advisories/25787
  - http://secunia.com/advisories/28027
  - http://secunia.com/advisories/28050
  - http://secunia.com/advisories/29032
  - http://secunia.com/advisories/29303
  - http://secunia.com/advisories/29889
  - http://secunia.com/advisories/31255
  - http://secunia.com/advisories/31492
  - http://secunia.com/advisories/37471
  - http://www.debian.org/security/2008/dsa-1551
  - http://www.debian.org/security/2008/dsa-1620
  - http://www.mandriva.com/security/advisories?name=MDKSA-2007:099
  - http://www.novell.com/linux/security/advisories/2007_13_sr.html
  - http://www.python.org/download/releases/2.5.1/NEWS.txt
  - http://www.redhat.com/support/errata/RHSA-2007-1076.html
  - http://www.redhat.com/support/errata/RHSA-2007-1077.html
  - http://www.redhat.com/support/errata/RHSA-2008-0629.html
  - http://www.securityfocus.com/archive/1/archive/1/469294/30/6450/threaded
  - http://www.securityfocus.com/archive/1/archive/1/488457/100/0/threaded
  - http://www.securityfocus.com/archive/1/archive/1/507985/100/0/threaded
  - http://www.securityfocus.com/bid/23887
  - http://www.trustix.org/errata/2007/0019/
  - http://www.ubuntu.com/usn/usn-585-1
  - http://www.vmware.com/security/advisories/VMSA-2009-0016.html
  - http://www.vupen.com/english/advisories/2007/1465
  - http://www.vupen.com/english/advisories/2008/0637
  - http://www.vupen.com/english/advisories/2009/3316
  - http://xforce.iss.net/xforce/xfdb/34060
  - https://bugzilla.redhat.com/bugzilla/show_bug.cgi?id=235093
  - https://exchange.xforce.ibmcloud.com/vulnerabilities/34060
  - https://issues.rpath.com/browse/RPL-1358
  source_url: https://ossindex.net/resource/package/8399917114/vulnerabilities
- id: ossindex:nuget:python2x86:325478
  title: '[CVE-2007-4559]  Improper Limitation of a Pathname to a Restricted Directory
    ("Path Traversal")'
  description: Directory traversal vulnerability in the (1) extract and (2) extractall
    functions in the tarfile module in Python allows user-assisted remote attackers
    to overwrite arbitrary files via a .. (dot dot) sequence in filenames in a TAR
    archive, a related issue to CVE-2001-1267.
  affected_package: python2x86
  vulnerable_versions:
  - "*"
  package_manager: nuget
  cve:
  - CVE-2007-4559
  disclosed_date: 2007-08-28
  created_date: 2007-08-28
  last_modified_date: 2017-04-19
  credit:
  - OSSIndex
  references:
  - http://mail.python.org/pipermail/python-dev/2007-August/074290.html
  - http://mail.python.org/pipermail/python-dev/2007-August/074292.html
  - http://secunia.com/advisories/26623
  - http://www.vupen.com/english/advisories/2007/3022
  - https://bugzilla.redhat.com/show_bug.cgi?id=263261
  source_url: https://ossindex.net/resource/package/8399917114/vulnerabilities
- id: ossindex:nuget:python2x86:325854
  title: "[CVE-2007-4965]  Numeric Errors"
  description: Multiple integer overflows in the imageop module in Python 2.5.1 and
    earlier allow context-dependent attackers to cause a denial of service (application
    crash) and possibly obtain sensitive information (memory contents) via crafted
    arguments to (1) the tovideo method, and unspecified other vectors related to
    (2) imageop.c, (3) rbgimgmodule.c, and other files, which trigger heap-based buffer
    overflows.
  affected_package: python2x86
  vulnerable_versions:
  - 1.5.2
  - '1.6'
  - 1.6.1
  - '2.0'
  - 2.0.1
  - '2.1'
  - 2.1.1
  - 2.1.2
  - 2.1.3
  - '2.2'
  - 2.2.1
  - 2.2.2
  - 2.2.3
  - '2.3'
  - 2.3.1
  - 2.3.2
  - 2.3.3
  - 2.3.4
  - 2.3.5
  - 2.3.6
  - '2.4'
  - 2.4.1
  - 2.4.2
  - 2.4.3
  - 2.4.4
  - '2.5'
  - 2.5.1
  package_manager: nuget
  cve:
  - CVE-2007-4965
  disclosed_date: 2007-09-18
  created_date: 2007-09-18
  last_modified_date: 2017-04-19
  credit:
  - OSSIndex
  references:
  - http://bugs.gentoo.org/show_bug.cgi?id=192876
  - http://docs.info.apple.com/article.html?artnum=307179
  - http://lists.apple.com/archives/security-announce/2007/Dec/msg00002.html
  - http://lists.apple.com/archives/security-announce/2009/Feb/msg00000.html
  - http://lists.grok.org.uk/pipermail/full-disclosure/2007-September/065826.html
  - http://lists.opensuse.org/opensuse-security-announce/2008-02/msg00003.html
  - http://lists.vmware.com/pipermail/security-announce/2008/000005.html
  - http://secunia.com/advisories/26837
  - http://secunia.com/advisories/27460
  - http://secunia.com/advisories/27562
  - http://secunia.com/advisories/27872
  - http://secunia.com/advisories/28136
  - http://secunia.com/advisories/28480
  - http://secunia.com/advisories/28838
  - http://secunia.com/advisories/29032
  - http://secunia.com/advisories/29303
  - http://secunia.com/advisories/29889
  - http://secunia.com/advisories/31255
  - http://secunia.com/advisories/31492
  - http://secunia.com/advisories/33937
  - http://secunia.com/advisories/37471
  - http://secunia.com/advisories/38675
  - http://support.apple.com/kb/HT3438
  - http://support.avaya.com/css/P8/documents/100074697
  - http://wiki.rpath.com/wiki/Advisories:rPSA-2007-0254
  - http://www.debian.org/security/2008/dsa-1551
  - http://www.debian.org/security/2008/dsa-1620
  - http://www.gentoo.org/security/en/glsa/glsa-200711-07.xml
  - http://www.mandriva.com/security/advisories?name=MDVSA-2008:012
  - http://www.mandriva.com/security/advisories?name=MDVSA-2008:013
  - http://www.redhat.com/support/errata/RHSA-2007-1076.html
  - http://www.redhat.com/support/errata/RHSA-2008-0629.html
  - http://www.securityfocus.com/archive/1/archive/1/487990/100/0/threaded
  - http://www.securityfocus.com/archive/1/archive/1/488457/100/0/threaded
  - http://www.securityfocus.com/archive/1/archive/1/507985/100/0/threaded
  - http://www.securityfocus.com/bid/25696
  - http://www.ubuntu.com/usn/usn-585-1
  - http://www.us-cert.gov/cas/techalerts/TA07-352A.html
  - http://www.vmware.com/security/advisories/VMSA-2009-0016.html
  - http://www.vupen.com/english/advisories/2007/3201
  - http://www.vupen.com/english/advisories/2007/4238
  - http://www.vupen.com/english/advisories/2008/0637
  - http://www.vupen.com/english/advisories/2009/3316
  - http://xforce.iss.net/xforce/xfdb/36653
  - https://exchange.xforce.ibmcloud.com/vulnerabilities/36653
  - https://issues.rpath.com/browse/RPL-1885
  - https://www.redhat.com/archives/fedora-package-announce/2007-October/msg00378.html
  source_url: https://ossindex.net/resource/package/8399917114/vulnerabilities
- id: ossindex:nuget:python2x86:329166
  title: "[CVE-2008-1679]  Numeric Errors"
  description: 'Multiple integer overflows in imageop.c in Python before 2.5.3 allow
    context-dependent attackers to cause a denial of service (crash) and possibly
    execute arbitrary code via crafted images that trigger heap-based buffer overflows.  NOTE:
    this issue is due to an incomplete fix for CVE-2007-4965.'
  affected_package: python2x86
  vulnerable_versions:
  - '2.4'
  - 2.5.2
  package_manager: nuget
  cve:
  - CVE-2008-1679
  disclosed_date: 2008-04-22
  created_date: 2008-04-22
  last_modified_date: 2017-04-19
  credit:
  - OSSIndex
  references:
  - http://bugs.python.org/issue1179
  - http://bugs.python.org/msg64682
  - http://lists.apple.com/archives/security-announce/2009/Feb/msg00000.html
  - http://lists.opensuse.org/opensuse-security-announce/2008-08/msg00006.html
  - http://secunia.com/advisories/29889
  - http://secunia.com/advisories/29955
  - http://secunia.com/advisories/30872
  - http://secunia.com/advisories/31255
  - http://secunia.com/advisories/31358
  - http://secunia.com/advisories/31365
  - http://secunia.com/advisories/31518
  - http://secunia.com/advisories/31687
  - http://secunia.com/advisories/33937
  - http://secunia.com/advisories/38675
  - http://security.gentoo.org/glsa/glsa-200807-01.xml
  - http://slackware.com/security/viewer.php?l=slackware-security&y=2008&m=slackware-security.525289
  - http://support.apple.com/kb/HT3438
  - http://support.avaya.com/css/P8/documents/100074697
  - http://wiki.rpath.com/wiki/Advisories:rPSA-2008-0149
  - http://www.debian.org/security/2008/dsa-1551
  - http://www.debian.org/security/2008/dsa-1620
  - http://www.mandriva.com/security/advisories?name=MDVSA-2008:163
  - http://www.mandriva.com/security/advisories?name=MDVSA-2008:164
  - http://www.novell.com/support/search.do?cmd=displayKC&docType=kc&externalId=InfoDocument-patchbuilder-readme5032900
  - http://www.ubuntu.com/usn/usn-632-1
  - http://xforce.iss.net/xforce/xfdb/41958
  - https://exchange.xforce.ibmcloud.com/vulnerabilities/41958
  - https://issues.rpath.com/browse/RPL-2424
  source_url: https://ossindex.net/resource/package/8399917114/vulnerabilities
- id: ossindex:nuget:python2x86:329207
  title: "[CVE-2008-1721]  Numeric Errors"
  description: Integer signedness error in the zlib extension module in Python 2.5.2
    and earlier allows remote attackers to execute arbitrary code via a negative signed
    integer, which triggers insufficient memory allocation and a buffer overflow.
  affected_package: python2x86
  vulnerable_versions:
  - 2.5.2
  package_manager: nuget
  cve:
  - CVE-2008-1721
  disclosed_date: 2008-04-10
  created_date: 2008-04-10
  last_modified_date: 2017-04-19
  credit:
  - OSSIndex
  references:
  - http://bugs.python.org/issue2586
  - http://lists.apple.com/archives/security-announce/2009/Feb/msg00000.html
  - http://secunia.com/advisories/29889
  - http://secunia.com/advisories/29955
  - http://secunia.com/advisories/30872
  - http://secunia.com/advisories/31255
  - http://secunia.com/advisories/31358
  - http://secunia.com/advisories/31365
  - http://secunia.com/advisories/33937
  - http://secunia.com/advisories/37471
  - http://secunia.com/advisories/38675
  - http://security.gentoo.org/glsa/glsa-200807-01.xml
  - http://securityreason.com/securityalert/3802
  - http://slackware.com/security/viewer.php?l=slackware-security&y=2008&m=slackware-security.525289
  - http://support.apple.com/kb/HT3438
  - http://support.avaya.com/css/P8/documents/100074697
  - http://wiki.rpath.com/wiki/Advisories:rPSA-2008-0149
  - http://www.debian.org/security/2008/dsa-1551
  - http://www.debian.org/security/2008/dsa-1620
  - http://www.mandriva.com/security/advisories?name=MDVSA-2008:085
  - http://www.securityfocus.com/archive/1/archive/1/490690/100/0/threaded
  - http://www.securityfocus.com/archive/1/archive/1/507985/100/0/threaded
  - http://www.securityfocus.com/bid/28715
  - http://www.securitytracker.com/id?1019823
  - http://www.ubuntu.com/usn/usn-632-1
  - http://www.vmware.com/security/advisories/VMSA-2009-0016.html
  - http://www.vupen.com/english/advisories/2008/1229/references
  - http://www.vupen.com/english/advisories/2009/3316
  - http://xforce.iss.net/xforce/xfdb/41748
  - https://exchange.xforce.ibmcloud.com/vulnerabilities/41748
  - https://issues.rpath.com/browse/RPL-2444
  source_url: https://ossindex.net/resource/package/8399917114/vulnerabilities
- id: ossindex:nuget:python2x86:329370
  title: "[CVE-2008-1887]  Improper Restriction of Operations within the Bounds of
    a Memory Buffer"
  description: Python 2.5.2 and earlier allows context-dependent attackers to execute
    arbitrary code via multiple vectors that cause a negative size value to be provided
    to the PyString_FromStringAndSize function, which allocates less memory than expected
    when assert() is disabled and triggers a buffer overflow.
  affected_package: python2x86
  vulnerable_versions:
  - 1.5.2
  - '1.6'
  - 1.6.1
  - '2.0'
  - 2.0.1
  - '2.1'
  - 2.1.1
  - 2.1.2
  - 2.1.3
  - '2.2'
  - 2.2.1
  - 2.2.2
  - 2.2.3
  - '2.3'
  - 2.3.1
  - 2.3.2
  - 2.3.3
  - 2.3.4
  - 2.3.5
  - 2.3.6
  - '2.4'
  - 2.4.1
  - 2.4.2
  - 2.4.3
  - 2.4.4
  - '2.5'
  - 2.5.1
  - 2.5.2
  - 2.5_alpha_1
  - 2.5_alpha_2
  - 2.5_beta_1
  - 2.5_beta_2
  - 2.5_beta_3
  - 2.5_final
  - 2.5_release_candidate_1
  - 2.5_release_candidate_2
  package_manager: nuget
  cve:
  - CVE-2008-1887
  disclosed_date: 2008-04-18
  created_date: 2008-04-18
  last_modified_date: 2017-04-19
  credit:
  - OSSIndex
  references:
  - http://bugs.python.org/issue2587
  - http://lists.apple.com/archives/security-announce/2009/Feb/msg00000.html
  - http://lists.opensuse.org/opensuse-security-announce/2008-08/msg00006.html
  - http://secunia.com/advisories/29889
  - http://secunia.com/advisories/30872
  - http://secunia.com/advisories/31255
  - http://secunia.com/advisories/31365
  - http://secunia.com/advisories/31518
  - http://secunia.com/advisories/31687
  - http://secunia.com/advisories/33937
  - http://secunia.com/advisories/37471
  - http://security.gentoo.org/glsa/glsa-200807-01.xml
  - http://support.apple.com/kb/HT3438
  - http://wiki.rpath.com/wiki/Advisories:rPSA-2009-0122
  - http://www.debian.org/security/2008/dsa-1551
  - http://www.debian.org/security/2008/dsa-1620
  - http://www.novell.com/support/search.do?cmd=displayKC&docType=kc&externalId=InfoDocument-patchbuilder-readme5032900
  - http://www.securityfocus.com/archive/1/490776
  - http://www.securityfocus.com/archive/1/archive/1/506056/100/0/threaded
  - http://www.securityfocus.com/archive/1/archive/1/507985/100/0/threaded
  - http://www.securityfocus.com/bid/28749
  - http://www.ubuntu.com/usn/usn-632-1
  - http://www.vmware.com/security/advisories/VMSA-2009-0016.html
  - http://www.vupen.com/english/advisories/2009/3316
  - http://xforce.iss.net/xforce/xfdb/41944
  - https://exchange.xforce.ibmcloud.com/vulnerabilities/41944
  source_url: https://ossindex.net/resource/package/8399917114/vulnerabilities
- id: ossindex:nuget:python2x86:329781
  title: "[CVE-2008-2315]  Numeric Errors"
  description: 'Multiple integer overflows in Python 2.5.2 and earlier allow context-dependent
    attackers to have an unknown impact via vectors related to the (1) stringobject,
    (2) unicodeobject, (3) bufferobject, (4) longobject, (5) tupleobject, (6) stropmodule,
    (7) gcmodule, and (8) mmapmodule modules.  NOTE: The expandtabs integer overflows
    in stringobject and unicodeobject in 2.5.2 are covered by CVE-2008-5031.'
  affected_package: python2x86
  vulnerable_versions:
  - 1.5.2
  - '1.6'
  - 1.6.1
  - '2.0'
  - 2.0.1
  - '2.1'
  - 2.1.1
  - 2.1.2
  - 2.1.3
  - '2.2'
  - 2.2.1
  - 2.2.2
  - 2.2.3
  - '2.3'
  - 2.3.1
  - 2.3.2
  - 2.3.3
  - 2.3.4
  - 2.3.5
  - 2.3.6
  - 2.3.7
  - '2.4'
  - 2.4.1
  - 2.4.2
  - 2.4.3
  - 2.4.4
  - 2.4.5
  - '2.5'
  - 2.5.1
  - 2.5.2
  package_manager: nuget
  cve:
  - CVE-2008-2315
  disclosed_date: 2008-08-01
  created_date: 2008-08-01
  last_modified_date: 2017-04-19
  credit:
  - OSSIndex
  references:
  - http://bugs.gentoo.org/attachment.cgi?id=159418&action=view
  - http://bugs.gentoo.org/show_bug.cgi?id=230640
  - http://lists.apple.com/archives/security-announce/2009/Feb/msg00000.html
  - http://lists.opensuse.org/opensuse-security-announce/2008-08/msg00006.html
  - http://secunia.com/advisories/31305
  - http://secunia.com/advisories/31332
  - http://secunia.com/advisories/31358
  - http://secunia.com/advisories/31365
  - http://secunia.com/advisories/31518
  - http://secunia.com/advisories/31687
  - http://secunia.com/advisories/32793
  - http://secunia.com/advisories/33937
  - http://secunia.com/advisories/37471
  - http://secunia.com/advisories/38675
  - http://security.gentoo.org/glsa/glsa-200807-16.xml
  - http://slackware.com/security/viewer.php?l=slackware-security&y=2008&m=slackware-security.525289
  - http://support.apple.com/kb/HT3438
  - http://support.avaya.com/css/P8/documents/100074697
  - http://www.debian.org/security/2008/dsa-1667
  - http://www.mandriva.com/security/advisories?name=MDVSA-2008:163
  - http://www.mandriva.com/security/advisories?name=MDVSA-2008:164
  - http://www.novell.com/support/search.do?cmd=displayKC&docType=kc&externalId=InfoDocument-patchbuilder-readme5032900
  - http://www.openwall.com/lists/oss-security/2008/11/05/2
  - http://www.openwall.com/lists/oss-security/2008/11/05/3
  - http://www.securityfocus.com/archive/1/archive/1/507985/100/0/threaded
  - http://www.securityfocus.com/bid/30491
  - http://www.ubuntu.com/usn/usn-632-1
  - http://www.vmware.com/security/advisories/VMSA-2009-0016.html
  - http://www.vupen.com/english/advisories/2008/2288
  - http://www.vupen.com/english/advisories/2009/3316
  - http://xforce.iss.net/xforce/xfdb/44172
  - http://xforce.iss.net/xforce/xfdb/44173
  - https://exchange.xforce.ibmcloud.com/vulnerabilities/44172
  - https://exchange.xforce.ibmcloud.com/vulnerabilities/44173
  source_url: https://ossindex.net/resource/package/8399917114/vulnerabilities
- id: ossindex:nuget:python2x86:329782
  title: "[CVE-2008-2316]  Numeric Errors"
  description: Integer overflow in _hashopenssl.c in the hashlib module in Python
    2.5.2 and earlier might allow context-dependent attackers to defeat cryptographic
    digests, related to "partial hashlib hashing of data exceeding 4GB."
  affected_package: python2x86
  vulnerable_versions:
  - 1.5.2
  - 1.6.1
  - 2.0.1
  - 2.1.3
  - 2.2.3
  - 2.3.7
  - 2.4.5
  - 2.5.1
  - 2.5.2
  package_manager: nuget
  cve:
  - CVE-2008-2316
  disclosed_date: 2008-08-01
  created_date: 2008-08-01
  last_modified_date: 2017-04-19
  credit:
  - OSSIndex
  references:
  - http://bugs.gentoo.org/attachment.cgi?id=159422&action=view
  - http://bugs.gentoo.org/show_bug.cgi?id=230640
  - http://lists.apple.com/archives/security-announce/2009/Feb/msg00000.html
  - http://lists.opensuse.org/opensuse-security-announce/2008-08/msg00006.html
  - http://secunia.com/advisories/31305
  - http://secunia.com/advisories/31332
  - http://secunia.com/advisories/31358
  - http://secunia.com/advisories/31365
  - http://secunia.com/advisories/31473
  - http://secunia.com/advisories/31518
  - http://secunia.com/advisories/31687
  - http://secunia.com/advisories/33937
  - http://security.gentoo.org/glsa/glsa-200807-16.xml
  - http://slackware.com/security/viewer.php?l=slackware-security&y=2008&m=slackware-security.525289
  - http://support.apple.com/kb/HT3438
  - http://wiki.rpath.com/Advisories:rPSA-2008-0243
  - http://www.mandriva.com/security/advisories?name=MDVSA-2008:163
  - http://www.novell.com/support/search.do?cmd=displayKC&docType=kc&externalId=InfoDocument-patchbuilder-readme5032900
  - http://www.securityfocus.com/archive/1/archive/1/495445/100/0/threaded
  - http://www.securityfocus.com/bid/30491
  - http://www.ubuntu.com/usn/usn-632-1
  - http://www.vupen.com/english/advisories/2008/2288
  - http://xforce.iss.net/xforce/xfdb/44173
  - http://xforce.iss.net/xforce/xfdb/44174
  source_url: https://ossindex.net/resource/package/8399917114/vulnerabilities
- id: ossindex:nuget:python2x86:330571
  title: "[CVE-2008-3142]  Improper Restriction of Operations within the Bounds of
    a Memory Buffer"
  description: Multiple buffer overflows in Python 2.5.2 and earlier on 32bit platforms
    allow context-dependent attackers to cause a denial of service (crash) or have
    unspecified other impact via a long string that leads to incorrect memory allocation
    during Unicode string processing, related to the unicode_resize function and the
    PyMem_RESIZE macro.
  affected_package: python2x86
  vulnerable_versions:
  - 1.5.2
  - '1.6'
  - 1.6.1
  - '2.0'
  - 2.0.1
  - '2.1'
  - 2.1.1
  - 2.1.2
  - 2.1.3
  - '2.2'
  - 2.2.1
  - 2.2.2
  - 2.2.3
  - '2.3'
  - 2.3.1
  - 2.3.2
  - 2.3.3
  - 2.3.4
  - 2.3.5
  - 2.3.6
  - 2.3.7
  - '2.4'
  - 2.4.1
  - 2.4.2
  - 2.4.3
  - 2.4.4
  - 2.4.5
  - '2.5'
  - 2.5.1
  - 2.5.2
  package_manager: nuget
  cve:
  - CVE-2008-3142
  disclosed_date: 2008-08-01
  created_date: 2008-08-01
  last_modified_date: 2017-04-19
  credit:
  - OSSIndex
  references:
  - http://bugs.gentoo.org/show_bug.cgi?id=232137
  - http://bugs.python.org/file10825/issue2620-gps02-patch.txt
  - http://bugs.python.org/issue2620
  - http://lists.apple.com/archives/security-announce/2009/Feb/msg00000.html
  - http://lists.opensuse.org/opensuse-security-announce/2008-08/msg00006.html
  - http://secunia.com/advisories/31305
  - http://secunia.com/advisories/31332
  - http://secunia.com/advisories/31358
  - http://secunia.com/advisories/31365
  - http://secunia.com/advisories/31473
  - http://secunia.com/advisories/31518
  - http://secunia.com/advisories/31687
  - http://secunia.com/advisories/32793
  - http://secunia.com/advisories/33937
  - http://secunia.com/advisories/37471
  - http://security.gentoo.org/glsa/glsa-200807-16.xml
  - http://slackware.com/security/viewer.php?l=slackware-security&y=2008&m=slackware-security.525289
  - http://support.apple.com/kb/HT3438
  - http://wiki.rpath.com/Advisories:rPSA-2008-0243
  - http://www.debian.org/security/2008/dsa-1667
  - http://www.mandriva.com/security/advisories?name=MDVSA-2008:163
  - http://www.mandriva.com/security/advisories?name=MDVSA-2008:164
  - http://www.novell.com/support/search.do?cmd=displayKC&docType=kc&externalId=InfoDocument-patchbuilder-readme5032900
  - http://www.securityfocus.com/archive/1/archive/1/495445/100/0/threaded
  - http://www.securityfocus.com/archive/1/archive/1/507985/100/0/threaded
  - http://www.securityfocus.com/bid/30491
  - http://www.ubuntu.com/usn/usn-632-1
  - http://www.vmware.com/security/advisories/VMSA-2009-0016.html
  - http://www.vupen.com/english/advisories/2008/2288
  - http://www.vupen.com/english/advisories/2009/3316
  - http://xforce.iss.net/xforce/xfdb/44170
  - http://xforce.iss.net/xforce/xfdb/44173
  - https://exchange.xforce.ibmcloud.com/vulnerabilities/44170
  - https://exchange.xforce.ibmcloud.com/vulnerabilities/44173
  source_url: https://ossindex.net/resource/package/8399917114/vulnerabilities
- id: ossindex:nuget:python2x86:330572
  title: "[CVE-2008-3143]  Numeric Errors"
  description: Multiple integer overflows in Python before 2.5.2 might allow context-dependent
    attackers to have an unknown impact via vectors related to (1) Include/pymem.h;
    (2) _csv.c, (3) _struct.c, (4) arraymodule.c, (5) audioop.c, (6) binascii.c, (7)
    cPickle.c, (8) cStringIO.c, (9) cjkcodecs/multibytecodec.c, (10) datetimemodule.c,
    (11) md5.c, (12) rgbimgmodule.c, and (13) stropmodule.c in Modules/; (14) bufferobject.c,
    (15) listobject.c, and (16) obmalloc.c in Objects/; (17) Parser/node.c; and (18)
    asdl.c, (19) ast.c, (20) bltinmodule.c, and (21) compile.c in Python/, as addressed
    by "checks for integer overflows, contributed by Google."
  affected_package: python2x86
  vulnerable_versions:
  - 1.5.2
  - 1.6.1
  - 2.0.1
  - 2.1.3
  - 2.2.3
  - 2.3.7
  - 2.4.5
  - 2.5.1
  package_manager: nuget
  cve:
  - CVE-2008-3143
  disclosed_date: 2008-08-01
  created_date: 2008-08-01
  last_modified_date: 2017-04-19
  credit:
  - OSSIndex
  references:
  - http://bugs.gentoo.org/show_bug.cgi?id=232137
  - http://lists.opensuse.org/opensuse-security-announce/2008-08/msg00006.html
  - http://secunia.com/advisories/31332
  - http://secunia.com/advisories/31365
  - http://secunia.com/advisories/31473
  - http://secunia.com/advisories/31518
  - http://secunia.com/advisories/31687
  - http://secunia.com/advisories/32793
  - http://secunia.com/advisories/37471
  - http://security.gentoo.org/glsa/glsa-200807-16.xml
  - http://svn.python.org/view?rev=60793&view=rev
  - http://wiki.rpath.com/Advisories:rPSA-2008-0243
  - http://www.debian.org/security/2008/dsa-1667
  - http://www.mandriva.com/security/advisories?name=MDVSA-2008:163
  - http://www.mandriva.com/security/advisories?name=MDVSA-2008:164
  - http://www.novell.com/support/search.do?cmd=displayKC&docType=kc&externalId=InfoDocument-patchbuilder-readme5032900
  - http://www.python.org/download/releases/2.5.2/NEWS.txt
  - http://www.python.org/download/releases/2.6/NEWS.txt
  - http://www.securityfocus.com/archive/1/archive/1/495445/100/0/threaded
  - http://www.securityfocus.com/archive/1/archive/1/507985/100/0/threaded
  - http://www.securityfocus.com/bid/30491
  - http://www.ubuntu.com/usn/usn-632-1
  - http://www.vmware.com/security/advisories/VMSA-2009-0016.html
  - http://www.vupen.com/english/advisories/2008/2288
  - http://www.vupen.com/english/advisories/2009/3316
  source_url: https://ossindex.net/resource/package/8399917114/vulnerabilities
- id: ossindex:nuget:python2x86:330573
  title: "[CVE-2008-3144]  Numeric Errors"
  description: 'Multiple integer overflows in the PyOS_vsnprintf function in Python/mysnprintf.c
    in Python 2.5.2 and earlier allow context-dependent attackers to cause a denial
    of service (memory corruption) or have unspecified other impact via crafted input
    to string formatting operations.  NOTE: the handling of certain integer values
    is also affected by related integer underflows and an off-by-one error.'
  affected_package: python2x86
  vulnerable_versions:
  - 1.5.2
  - '1.6'
  - 1.6.1
  - '2.0'
  - 2.0.1
  - '2.1'
  - 2.1.1
  - 2.1.2
  - 2.1.3
  - '2.2'
  - 2.2.1
  - 2.2.2
  - 2.2.3
  - '2.3'
  - 2.3.1
  - 2.3.2
  - 2.3.3
  - 2.3.4
  - 2.3.5
  - 2.3.6
  - 2.3.7
  - '2.4'
  - 2.4.1
  - 2.4.2
  - 2.4.3
  - 2.4.4
  - 2.4.5
  - '2.5'
  - 2.5.1
  - 2.5.2
  package_manager: nuget
  cve:
  - CVE-2008-3144
  disclosed_date: 2008-08-01
  created_date: 2008-08-01
  last_modified_date: 2017-04-19
  credit:
  - OSSIndex
  references:
  - http://bugs.gentoo.org/show_bug.cgi?id=232137
  - http://bugs.python.org/issue2588
  - http://bugs.python.org/issue2589
  - http://lists.apple.com/archives/security-announce/2009/Feb/msg00000.html
  - http://lists.opensuse.org/opensuse-security-announce/2008-08/msg00006.html
  - http://secunia.com/advisories/31305
  - http://secunia.com/advisories/31332
  - http://secunia.com/advisories/31358
  - http://secunia.com/advisories/31365
  - http://secunia.com/advisories/31473
  - http://secunia.com/advisories/31518
  - http://secunia.com/advisories/31687
  - http://secunia.com/advisories/32793
  - http://secunia.com/advisories/33937
  - http://secunia.com/advisories/37471
  - http://security.gentoo.org/glsa/glsa-200807-16.xml
  - http://slackware.com/security/viewer.php?l=slackware-security&y=2008&m=slackware-security.525289
  - http://support.apple.com/kb/HT3438
  - http://svn.python.org/view?rev=63728&view=rev
  - http://svn.python.org/view?rev=63734&view=rev
  - http://svn.python.org/view?rev=63883&view=rev
  - http://wiki.rpath.com/Advisories:rPSA-2008-0243
  - http://www.debian.org/security/2008/dsa-1667
  - http://www.mandriva.com/security/advisories?name=MDVSA-2008:163
  - http://www.mandriva.com/security/advisories?name=MDVSA-2008:164
  - http://www.novell.com/support/search.do?cmd=displayKC&docType=kc&externalId=InfoDocument-patchbuilder-readme5032900
  - http://www.securityfocus.com/archive/1/archive/1/495445/100/0/threaded
  - http://www.securityfocus.com/archive/1/archive/1/507985/100/0/threaded
  - http://www.securityfocus.com/bid/30491
  - http://www.ubuntu.com/usn/usn-632-1
  - http://www.vmware.com/security/advisories/VMSA-2009-0016.html
  - http://www.vupen.com/english/advisories/2008/2288
  - http://www.vupen.com/english/advisories/2009/3316
  - http://xforce.iss.net/xforce/xfdb/44171
  - http://xforce.iss.net/xforce/xfdb/44173
  - https://exchange.xforce.ibmcloud.com/vulnerabilities/44171
  - https://exchange.xforce.ibmcloud.com/vulnerabilities/44173
  source_url: https://ossindex.net/resource/package/8399917114/vulnerabilities
- id: ossindex:nuget:python2x86:331511
  title: '[CVE-2008-4108]  Improper Link Resolution Before File Access ("Link Following")'
  description: 'Tools/faqwiz/move-faqwiz.sh (aka the generic FAQ wizard moving tool)
    in Python 2.4.5 might allow local users to overwrite arbitrary files via a symlink
    attack on a tmp$RANDOM.tmp temporary file.  NOTE: there may not be common usage
    scenarios in which tmp$RANDOM.tmp is located in an untrusted directory.'
  affected_package: python2x86
  vulnerable_versions:
  - 2.4.5
  package_manager: nuget
  cve:
  - CVE-2008-4108
  disclosed_date: 2008-09-18
  created_date: 2008-09-18
  last_modified_date: 2017-04-19
  credit:
  - OSSIndex
  references:
  - http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=498899
  - http://marc.info/?l=oss-security&m=122148330903513&w=2
  - http://marc.info/?l=oss-security&m=122152861617434&w=2
  - http://securityreason.com/securityalert/4274
  - http://www.securityfocus.com/bid/31184
  - http://www.securitytracker.com/id?1020904
  - http://www.vupen.com/english/advisories/2008/2659
  - http://xforce.iss.net/xforce/xfdb/45161
  - https://bugzilla.redhat.com/show_bug.cgi?id=462326
  source_url: https://ossindex.net/resource/package/8399917114/vulnerabilities
- id: ossindex:nuget:python2x86:332198
  title: "[CVE-2008-4864]  Numeric Errors"
  description: Multiple integer overflows in imageop.c in the imageop module in Python
    1.5.2 through 2.5.1 allow context-dependent attackers to break out of the Python
    VM and execute arbitrary code via large integer values in certain arguments to
    the crop function, leading to a buffer overflow, a different vulnerability than
    CVE-2007-4965 and CVE-2008-1679.
  affected_package: python2x86
  vulnerable_versions:
  - 1.5.2
  - '1.6'
  - 1.6.1
  - '2.0'
  - 2.0.1
  - '2.1'
  - 2.1.1
  - 2.1.2
  - 2.1.3
  - '2.2'
  - 2.2.1
  - 2.2.2
  - 2.2.3
  - '2.3'
  - 2.3.1
  - 2.3.2
  - 2.3.3
  - 2.3.4
  - 2.3.5
  - 2.3.6
  - '2.4'
  - 2.4.1
  - 2.4.2
  - 2.4.3
  - 2.4.4
  - '2.5'
  - 2.5.1
  package_manager: nuget
  cve:
  - CVE-2008-4864
  disclosed_date: 2008-11-01
  created_date: 2008-11-01
  last_modified_date: 2017-04-19
  credit:
  - OSSIndex
  references:
  - http://lists.apple.com/archives/security-announce/2009/Feb/msg00000.html
  - http://scary.beasts.org/security/CESA-2008-008.html
  - http://secunia.com/advisories/33937
  - http://secunia.com/advisories/37471
  - http://support.apple.com/kb/HT3438
  - http://svn.python.org/view/python/trunk/Modules/imageop.c?rev=66689&view=diff&r1=66689&r2=66688&p1=python/trunk/Modules/imageop.c&p2=/python/trunk/Modules/imageop.c
  - http://svn.python.org/view?rev=66689&view=rev
  - http://www.openwall.com/lists/oss-security/2008/10/27/2
  - http://www.openwall.com/lists/oss-security/2008/10/29/3
  - http://www.securityfocus.com/archive/1/archive/1/507985/100/0/threaded
  - http://www.securityfocus.com/bid/31932
  - http://www.securityfocus.com/bid/31976
  - http://www.vmware.com/security/advisories/VMSA-2009-0016.html
  - http://www.vupen.com/english/advisories/2009/3316
  - http://xforce.iss.net/xforce/xfdb/46606
  - https://exchange.xforce.ibmcloud.com/vulnerabilities/46606
  source_url: https://ossindex.net/resource/package/8399917114/vulnerabilities
- id: ossindex:nuget:python2x86:332363
  title: "[CVE-2008-5031]  Numeric Errors"
  description: 'Multiple integer overflows in Python 2.2.3 through 2.5.1, and 2.6,
    allow context-dependent attackers to have an unknown impact via a large integer
    value in the tabsize argument to the expandtabs method, as implemented by (1)
    the string_expandtabs function in Objects/stringobject.c and (2) the unicode_expandtabs
    function in Objects/unicodeobject.c.  NOTE: this vulnerability reportedly exists
    because of an incomplete fix for CVE-2008-2315.'
  affected_package: python2x86
  vulnerable_versions:
  - 2.2.3
  - 2.3.7
  - 2.4.6
  - 2.5.1
  - '2.6'
  package_manager: nuget
  cve:
  - CVE-2008-5031
  disclosed_date: 2008-11-10
  created_date: 2008-11-10
  last_modified_date: 2017-04-19
  credit:
  - OSSIndex
  references:
  - http://lists.apple.com/archives/security-announce/2009/Feb/msg00000.html
  - http://scary.beasts.org/security/CESA-2008-008.html
  - http://secunia.com/advisories/33937
  - http://secunia.com/advisories/35750
  - http://secunia.com/advisories/37471
  - http://security.gentoo.org/glsa/glsa-200907-16.xml
  - http://support.apple.com/kb/HT3438
  - http://svn.python.org/view/python/trunk/Objects/stringobject.c?rev=61350&view=diff&r1=61350&r2=61349&p1=python/trunk/Objects/stringobject.c&p2=/python/trunk/Objects/stringobject.c
  - http://svn.python.org/view/python/trunk/Objects/unicodeobject.c?rev=61350&view=diff&r1=61350&r2=61349&p1=python/trunk/Objects/unicodeobject.c&p2=/python/trunk/Objects/unicodeobject.c
  - http://svn.python.org/view?rev=61350&view=rev
  - http://www.openwall.com/lists/oss-security/2008/11/05/2
  - http://www.openwall.com/lists/oss-security/2008/11/05/3
  - http://www.securityfocus.com/archive/1/archive/1/507985/100/0/threaded
  - http://www.vmware.com/security/advisories/VMSA-2009-0016.html
  - http://www.vupen.com/english/advisories/2009/3316
  - http://xforce.iss.net/xforce/xfdb/46612
  - https://exchange.xforce.ibmcloud.com/vulnerabilities/46612
  source_url: https://ossindex.net/resource/package/8399917114/vulnerabilities
- id: ossindex:nuget:python2x86:333259
  title: "[CVE-2008-5983] Untrusted search path vulnerability in the PySys&#95;SetArgv
    API function in Python ..."
  description: Untrusted search path vulnerability in the PySys_SetArgv API function
    in Python 2.6 and earlier, and possibly later versions, prepends an empty string
    to sys.path when the argv[0] argument does not contain a path separator, which
    might allow local users to execute arbitrary code via a Trojan horse Python file
    in the current working directory.
  affected_package: python2x86
  vulnerable_versions:
  - 1.5.2
  - '1.6'
  - 1.6.1
  - '2.0'
  - 2.0.1
  - '2.1'
  - 2.1.1
  - 2.1.2
  - 2.1.3
  - '2.2'
  - 2.2.1
  - 2.2.2
  - 2.2.3
  - '2.3'
  - 2.3.1
  - 2.3.2
  - 2.3.3
  - 2.3.4
  - 2.3.5
  - 2.3.6
  - 2.3.7
  - '2.4'
  - 2.4.1
  - 2.4.2
  - 2.4.3
  - 2.4.4
  - 2.4.5
  - 2.4.6
  - '2.5'
  - 2.5.1
  - 2.5.2
  - 2.5.4
  - 2.6.0
  package_manager: nuget
  cve:
  - CVE-2008-5983
  disclosed_date: 2009-01-28
  created_date: 2009-01-28
  last_modified_date: 2017-04-19
  credit:
  - OSSIndex
  references:
  - http://lists.fedoraproject.org/pipermail/package-announce/2010-June/042751.html
  - http://secunia.com/advisories/34522
  - http://secunia.com/advisories/40194
  - http://secunia.com/advisories/42888
  - http://secunia.com/advisories/50858
  - http://secunia.com/advisories/51024
  - http://secunia.com/advisories/51040
  - http://secunia.com/advisories/51087
  - http://security.gentoo.org/glsa/glsa-200903-41.xml
  - http://security.gentoo.org/glsa/glsa-200904-06.xml
  - http://www.mail-archive.com/debian-bugs-dist@lists.debian.org/msg586010.html
  - http://www.nabble.com/Bug-484305%3A-bicyclerepair%3A-bike.vim-imports-untrusted-python-files-from-cwd-td18848099.html
  - http://www.nabble.com/Bug-484305:-bicyclerepair:-bike.vim-imports-untrusted-python-files-from-cwd-td18848099.html
  - http://www.openwall.com/lists/oss-security/2009/01/26/2
  - http://www.openwall.com/lists/oss-security/2009/01/28/5
  - http://www.openwall.com/lists/oss-security/2009/01/30/2
  - http://www.redhat.com/support/errata/RHSA-2011-0027.html
  - http://www.ubuntu.com/usn/USN-1596-1
  - http://www.ubuntu.com/usn/USN-1613-1
  - http://www.ubuntu.com/usn/USN-1613-2
  - http://www.ubuntu.com/usn/USN-1616-1
  - http://www.vupen.com/english/advisories/2010/1448
  - http://www.vupen.com/english/advisories/2011/0122
  - https://bugzilla.redhat.com/show_bug.cgi?id=482814
  source_url: https://ossindex.net/resource/package/8399917114/vulnerabilities
- id: ossindex:nuget:python2x86:338508
  title: "[CVE-2009-4134]  Improper Restriction of Operations within the Bounds of
    a Memory Buffer"
  description: Buffer underflow in the rgbimg module in Python 2.5 allows remote attackers
    to cause a denial of service (application crash) via a large ZSIZE value in a
    black-and-white (aka B/W) RGB image that triggers an invalid pointer dereference.
  affected_package: python2x86
  vulnerable_versions:
  - '2.5'
  package_manager: nuget
  cve:
  - CVE-2009-4134
  disclosed_date: 2010-05-27
  created_date: 2010-05-27
  last_modified_date: 2017-04-19
  credit:
  - OSSIndex
  references:
  - http://bugs.python.org/issue8678
  - http://lists.apple.com/archives/security-announce/2010//Nov/msg00000.html
  - http://lists.opensuse.org/opensuse-security-announce/2011-01/msg00006.html
  - http://secunia.com/advisories/42888
  - http://secunia.com/advisories/43068
  - http://secunia.com/advisories/43364
  - http://support.apple.com/kb/HT4435
  - http://www.mandriva.com/security/advisories?name=MDVSA-2010:215
  - http://www.redhat.com/support/errata/RHSA-2011-0027.html
  - http://www.redhat.com/support/errata/RHSA-2011-0260.html
  - http://www.securityfocus.com/bid/40361
  - http://www.vupen.com/english/advisories/2011/0122
  - http://www.vupen.com/english/advisories/2011/0212
  - http://www.vupen.com/english/advisories/2011/0413
  - https://bugzilla.redhat.com/show_bug.cgi?id=541698
  source_url: https://ossindex.net/resource/package/8399917114/vulnerabilities
- id: ossindex:nuget:python2x86:340859
  title: "[CVE-2010-1449]  Numeric Errors"
  description: 'Integer overflow in rgbimgmodule.c in the rgbimg module in Python
    2.5 allows remote attackers to have an unspecified impact via a large image that
    triggers a buffer overflow.  NOTE: this vulnerability exists because of an incomplete
    fix for CVE-2008-3143.12.'
  affected_package: python2x86
  vulnerable_versions:
  - '2.5'
  package_manager: nuget
  cve:
  - CVE-2010-1449
  disclosed_date: 2010-05-27
  created_date: 2010-05-27
  last_modified_date: 2017-04-19
  credit:
  - OSSIndex
  references:
  - http://bugs.python.org/issue8678
  - http://lists.apple.com/archives/security-announce/2010//Nov/msg00000.html
  - http://lists.opensuse.org/opensuse-security-announce/2011-01/msg00006.html
  - http://secunia.com/advisories/42888
  - http://secunia.com/advisories/43068
  - http://secunia.com/advisories/43364
  - http://support.apple.com/kb/HT4435
  - http://www.mandriva.com/security/advisories?name=MDVSA-2010:215
  - http://www.redhat.com/support/errata/RHSA-2011-0027.html
  - http://www.redhat.com/support/errata/RHSA-2011-0260.html
  - http://www.securityfocus.com/bid/40363
  - http://www.vupen.com/english/advisories/2011/0122
  - http://www.vupen.com/english/advisories/2011/0212
  - http://www.vupen.com/english/advisories/2011/0413
  - https://bugzilla.redhat.com/show_bug.cgi?id=541698
  source_url: https://ossindex.net/resource/package/8399917114/vulnerabilities
- id: ossindex:nuget:python2x86:340860
  title: "[CVE-2010-1450]  Improper Restriction of Operations within the Bounds of
    a Memory Buffer"
  description: Multiple buffer overflows in the RLE decoder in the rgbimg module in
    Python 2.5 allow remote attackers to have an unspecified impact via an image file
    containing crafted data that triggers improper processing within the (1) longimagedata
    or (2) expandrow function.
  affected_package: python2x86
  vulnerable_versions:
  - '2.5'
  package_manager: nuget
  cve:
  - CVE-2010-1450
  disclosed_date: 2010-05-27
  created_date: 2010-05-27
  last_modified_date: 2017-04-19
  credit:
  - OSSIndex
  references:
  - http://bugs.python.org/issue8678
  - http://lists.apple.com/archives/security-announce/2010//Nov/msg00000.html
  - http://lists.opensuse.org/opensuse-security-announce/2011-01/msg00006.html
  - http://secunia.com/advisories/42888
  - http://secunia.com/advisories/43068
  - http://secunia.com/advisories/43364
  - http://support.apple.com/kb/HT4435
  - http://www.mandriva.com/security/advisories?name=MDVSA-2010:215
  - http://www.redhat.com/support/errata/RHSA-2011-0027.html
  - http://www.redhat.com/support/errata/RHSA-2011-0260.html
  - http://www.securityfocus.com/bid/40365
  - http://www.vupen.com/english/advisories/2011/0122
  - http://www.vupen.com/english/advisories/2011/0212
  - http://www.vupen.com/english/advisories/2011/0413
  - https://bugzilla.redhat.com/show_bug.cgi?id=541698
  source_url: https://ossindex.net/resource/package/8399917114/vulnerabilities
- id: ossindex:nuget:python2x86:341036
  title: "[CVE-2010-1634]  Numeric Errors"
  description: 'Multiple integer overflows in audioop.c in the audioop module in Python
    2.6, 2.7, 3.1, and 3.2 allow context-dependent attackers to cause a denial of
    service (application crash) via a large fragment, as demonstrated by a call to
    audioop.lin2lin with a long string in the first argument, leading to a buffer
    overflow.  NOTE: this vulnerability exists because of an incorrect fix for CVE-2008-3143.5.'
  affected_package: python2x86
  vulnerable_versions:
  - '2.6'
  - '2.7'
  - '3.1'
  - '3.2'
  package_manager: nuget
  cve:
  - CVE-2010-1634
  disclosed_date: 2010-05-27
  created_date: 2010-05-27
  last_modified_date: 2017-04-19
  credit:
  - OSSIndex
  references:
  - http://bugs.python.org/issue8674
  - http://lists.apple.com/archives/Security-announce/2011//Oct/msg00003.html
  - http://lists.fedoraproject.org/pipermail/package-announce/2010-June/042751.html
  - http://lists.opensuse.org/opensuse-security-announce/2010-12/msg00006.html
  - http://lists.opensuse.org/opensuse-security-announce/2011-01/msg00006.html
  - http://secunia.com/advisories/39937
  - http://secunia.com/advisories/40194
  - http://secunia.com/advisories/42888
  - http://secunia.com/advisories/43068
  - http://secunia.com/advisories/50858
  - http://secunia.com/advisories/51024
  - http://secunia.com/advisories/51040
  - http://secunia.com/advisories/51087
  - http://support.apple.com/kb/HT5002
  - http://svn.python.org/view?rev=81045&view=rev
  - http://svn.python.org/view?rev=81079&view=rev
  - http://www.redhat.com/support/errata/RHSA-2011-0027.html
  - http://www.securityfocus.com/bid/40370
  - http://www.ubuntu.com/usn/USN-1596-1
  - http://www.ubuntu.com/usn/USN-1613-1
  - http://www.ubuntu.com/usn/USN-1613-2
  - http://www.ubuntu.com/usn/USN-1616-1
  - http://www.vupen.com/english/advisories/2010/1448
  - http://www.vupen.com/english/advisories/2011/0122
  - http://www.vupen.com/english/advisories/2011/0212
  - https://bugzilla.redhat.com/show_bug.cgi?id=590690
  source_url: https://ossindex.net/resource/package/8399917114/vulnerabilities
- id: ossindex:nuget:python2x86:341459
  title: "[CVE-2010-2089]  Improper Restriction of Operations within the Bounds of
    a Memory Buffer"
  description: The audioop module in Python 2.7 and 3.2 does not verify the relationships
    between size arguments and byte string lengths, which allows context-dependent
    attackers to cause a denial of service (memory corruption and application crash)
    via crafted arguments, as demonstrated by a call to audioop.reverse with a one-byte
    string, a different vulnerability than CVE-2010-1634.
  affected_package: python2x86
  vulnerable_versions:
  - '2.7'
  - '3.2'
  package_manager: nuget
  cve:
  - CVE-2010-2089
  disclosed_date: 2010-05-27
  created_date: 2010-05-27
  last_modified_date: 2017-04-19
  credit:
  - OSSIndex
  references:
  - http://bugs.python.org/issue7673
  - http://lists.apple.com/archives/Security-announce/2011//Oct/msg00003.html
  - http://lists.fedoraproject.org/pipermail/package-announce/2010-June/042751.html
  - http://lists.opensuse.org/opensuse-security-announce/2010-12/msg00006.html
  - http://lists.opensuse.org/opensuse-security-announce/2011-01/msg00006.html
  - http://secunia.com/advisories/40194
  - http://secunia.com/advisories/42888
  - http://secunia.com/advisories/43068
  - http://secunia.com/advisories/50858
  - http://secunia.com/advisories/51024
  - http://secunia.com/advisories/51040
  - http://secunia.com/advisories/51087
  - http://support.apple.com/kb/HT5002
  - http://www.redhat.com/support/errata/RHSA-2011-0027.html
  - http://www.securityfocus.com/bid/40863
  - http://www.ubuntu.com/usn/USN-1596-1
  - http://www.ubuntu.com/usn/USN-1613-1
  - http://www.ubuntu.com/usn/USN-1613-2
  - http://www.ubuntu.com/usn/USN-1616-1
  - http://www.vupen.com/english/advisories/2010/1448
  - http://www.vupen.com/english/advisories/2011/0122
  - http://www.vupen.com/english/advisories/2011/0212
  - https://bugzilla.redhat.com/show_bug.cgi?id=598197
  source_url: https://ossindex.net/resource/package/8399917114/vulnerabilities
- id: ossindex:nuget:python2x86:342754
  title: "[CVE-2010-3492] The asyncore module in Python before 3.2 does not properly
    handle unsuccessful c..."
  description: The asyncore module in Python before 3.2 does not properly handle unsuccessful
    calls to the accept function, and does not have accompanying documentation describing
    how daemon applications should handle unsuccessful calls to the accept function,
    which makes it easier for remote attackers to conduct denial of service attacks
    that terminate these applications via network connections.
  affected_package: python2x86
  vulnerable_versions:
  - 0.9.0
  - 0.9.1
  - '1.2'
  - '1.3'
  - 1.5.2
  - '1.6'
  - 1.6.1
  - '2.0'
  - 2.0.1
  - '2.1'
  - 2.1.1
  - 2.1.2
  - 2.1.3
  - '2.2'
  - 2.2.1
  - 2.2.2
  - 2.2.3
  - '2.3'
  - 2.3.1
  - 2.3.2
  - 2.3.3
  - 2.3.4
  - 2.3.5
  - 2.3.7
  - '2.4'
  - 2.4.1
  - 2.4.2
  - 2.4.3
  - 2.4.4
  - 2.4.6
  - '2.5'
  - 2.5.1
  - 2.5.2
  - 2.5.3
  - 2.5.4
  - '2.6'
  - 2.6.1
  - 2.6.4
  - '2.7'
  - '3.0'
  - 3.0.1
  - 3.1.1
  - 3.1.2
  package_manager: nuget
  cve:
  - CVE-2010-3492
  disclosed_date: 2010-10-19
  created_date: 2010-10-19
  last_modified_date: 2017-04-19
  credit:
  - OSSIndex
  references:
  - http://bugs.python.org/issue6706
  - http://www.mandriva.com/security/advisories?name=MDVSA-2010:215
  - http://www.mandriva.com/security/advisories?name=MDVSA-2010:216
  - http://www.openwall.com/lists/oss-security/2010/09/09/6
  - http://www.openwall.com/lists/oss-security/2010/09/11/2
  - http://www.openwall.com/lists/oss-security/2010/09/22/3
  - http://www.openwall.com/lists/oss-security/2010/09/24/3
  source_url: https://ossindex.net/resource/package/8399917114/vulnerabilities
- id: ossindex:nuget:python2x86:342755
  title: '[CVE-2010-3493]  Concurrent Execution using Shared Resource with Improper
    Synchronization ("Race Condition")'
  description: Multiple race conditions in smtpd.py in the smtpd module in Python
    2.6, 2.7, 3.1, and 3.2 alpha allow remote attackers to cause a denial of service
    (daemon outage) by establishing and then immediately closing a TCP connection,
    leading to the accept function having an unexpected return value of None, an unexpected
    value of None for the address, or an ECONNABORTED, EAGAIN, or EWOULDBLOCK error,
    or the getpeername function having an ENOTCONN error, a related issue to CVE-2010-3492.
  affected_package: python2x86
  vulnerable_versions:
  - '2.6'
  - '2.7'
  - '3.1'
  - '3.2'
  package_manager: nuget
  cve:
  - CVE-2010-3493
  disclosed_date: 2010-10-19
  created_date: 2010-10-19
  last_modified_date: 2017-04-19
  credit:
  - OSSIndex
  references:
  - http://bugs.python.org/issue6706
  - http://bugs.python.org/issue9129
  - http://lists.opensuse.org/opensuse-security-announce/2010-12/msg00006.html
  - http://lists.opensuse.org/opensuse-security-announce/2011-01/msg00006.html
  - http://secunia.com/advisories/43068
  - http://secunia.com/advisories/50858
  - http://secunia.com/advisories/51024
  - http://secunia.com/advisories/51040
  - http://svn.python.org/view/python/branches/py3k/Lib/smtpd.py?r1=84289&r2=84288&pathrev=84289
  - http://svn.python.org/view?view=rev&revision=84289
  - http://www.mandriva.com/security/advisories?name=MDVSA-2010:215
  - http://www.mandriva.com/security/advisories?name=MDVSA-2010:216
  - http://www.openwall.com/lists/oss-security/2010/09/09/6
  - http://www.openwall.com/lists/oss-security/2010/09/11/2
  - http://www.openwall.com/lists/oss-security/2010/09/22/3
  - http://www.openwall.com/lists/oss-security/2010/09/24/3
  - http://www.securityfocus.com/bid/44533
  - http://www.ubuntu.com/usn/USN-1596-1
  - http://www.ubuntu.com/usn/USN-1613-1
  - http://www.ubuntu.com/usn/USN-1613-2
  - http://www.vupen.com/english/advisories/2011/0212
  - https://bugs.launchpad.net/zodb/%20bug/135108
  - https://bugs.launchpad.net/zodb/+bug/135108
  - https://bugzilla.redhat.com/show_bug.cgi?id=632200
  source_url: https://ossindex.net/resource/package/8399917114/vulnerabilities
- id: ossindex:nuget:python2x86:345269
  title: "[CVE-2011-1015]  Information Exposure"
  description: The is_cgi method in CGIHTTPServer.py in the CGIHTTPServer module in
    Python 2.5, 2.6, and 3.0 allows remote attackers to read script source code via
    an HTTP GET request that lacks a / (slash) character at the beginning of the URI.
  affected_package: python2x86
  vulnerable_versions:
  - '2.5'
  - '2.6'
  - '3.0'
  package_manager: nuget
  cve:
  - CVE-2011-1015
  disclosed_date: 2011-05-09
  created_date: 2011-05-09
  last_modified_date: 2017-04-19
  credit:
  - OSSIndex
  references:
  - http://bugs.python.org/issue2254
  - http://hg.python.org/cpython/rev/c6c4398293bd/
  - http://openwall.com/lists/oss-security/2011/02/23/27
  - http://openwall.com/lists/oss-security/2011/02/24/10
  - http://secunia.com/advisories/50858
  - http://secunia.com/advisories/51024
  - http://secunia.com/advisories/51040
  - http://securitytracker.com/id?1025489
  - http://svn.python.org/view?view=revision&revision=71303
  - http://www.mandriva.com/security/advisories?name=MDVSA-2011:096
  - http://www.securityfocus.com/bid/46541
  - http://www.ubuntu.com/usn/USN-1596-1
  - http://www.ubuntu.com/usn/USN-1613-1
  - http://www.ubuntu.com/usn/USN-1613-2
  - https://bugzilla.redhat.com/show_bug.cgi?id=680094
  source_url: https://ossindex.net/resource/package/8399917114/vulnerabilities
- id: ossindex:nuget:python2x86:345717
  title: "[CVE-2011-1521]  Resource Management Errors"
  description: 'The urllib and urllib2 modules in Python 2.x before 2.7.2 and 3.x
    before 3.2.1 process Location headers that specify redirection to file: URLs,
    which makes it easier for remote attackers to obtain sensitive information or
    cause a denial of service (resource consumption) via a crafted URL, as demonstrated
    by the file:///etc/passwd and file:///dev/zero URLs.'
  affected_package: python2x86
  vulnerable_versions:
  - '2.0'
  - 2.0.1
  - '2.1'
  - 2.1.1
  - 2.1.2
  - 2.1.3
  - '2.2'
  - 2.2.1
  - 2.2.2
  - 2.2.3
  - '2.3'
  - 2.3.1
  - 2.3.2
  - 2.3.3
  - 2.3.4
  - 2.3.5
  - 2.3.7
  - '2.4'
  - 2.4.1
  - 2.4.2
  - 2.4.3
  - 2.4.4
  - 2.4.6
  - '2.5'
  - 2.5.1
  - 2.5.2
  - 2.5.3
  - 2.5.4
  - '2.6'
  - 2.6.1
  - 2.6.4
  - 2.6.5
  - 2.6.6
  - 2.6.7
  - '2.7'
  - 2.7.1
  - '3.0'
  - 3.0.1
  - '3.1'
  - 3.1.1
  - 3.1.2
  - 3.1.3
  - '3.2'
  package_manager: nuget
  cve:
  - CVE-2011-1521
  disclosed_date: 2011-05-24
  created_date: 2011-05-24
  last_modified_date: 2017-04-19
  credit:
  - OSSIndex
  references:
  - http://bugs.python.org/issue11662
  - http://hg.python.org/cpython/file/96a6c128822b/Misc/NEWS
  - http://hg.python.org/cpython/file/b2934d98dac1/Misc/NEWS
  - http://hg.python.org/cpython/rev/96a6c128822b/
  - http://hg.python.org/cpython/rev/b2934d98dac1/
  - http://lists.apple.com/archives/Security-announce/2011//Oct/msg00003.html
  - http://lists.opensuse.org/opensuse-security-announce/2011-05/msg00005.html
  - http://openwall.com/lists/oss-security/2011/03/24/5
  - http://openwall.com/lists/oss-security/2011/03/28/2
  - http://openwall.com/lists/oss-security/2011/09/11/1
  - http://openwall.com/lists/oss-security/2011/09/13/2
  - http://openwall.com/lists/oss-security/2011/09/15/5
  - http://secunia.com/advisories/50858
  - http://secunia.com/advisories/51024
  - http://secunia.com/advisories/51040
  - http://securitytracker.com/id?1025488
  - http://support.apple.com/kb/HT5002
  - http://www.mandriva.com/security/advisories?name=MDVSA-2011:096
  - http://www.ubuntu.com/usn/USN-1592-1
  - http://www.ubuntu.com/usn/USN-1596-1
  - http://www.ubuntu.com/usn/USN-1613-1
  - http://www.ubuntu.com/usn/USN-1613-2
  - https://bugzilla.redhat.com/show_bug.cgi?id=690560
  - https://bugzilla.redhat.com/show_bug.cgi?id=737366
  - https://www.djangoproject.com/weblog/2011/sep/09/
  - https://www.djangoproject.com/weblog/2011/sep/10/127/
  source_url: https://ossindex.net/resource/package/8399917114/vulnerabilities
- id: ossindex:nuget:python2x86:348506
  title: '[CVE-2011-4940]  Improper Neutralization of Input During Web Page Generation
    ("Cross-site Scripting")'
  description: The list_directory function in Lib/SimpleHTTPServer.py in SimpleHTTPServer
    in Python before 2.5.6c1, 2.6.x before 2.6.7 rc2, and 2.7.x before 2.7.2 does
    not place a charset parameter in the Content-Type HTTP header, which makes it
    easier for remote attackers to conduct cross-site scripting (XSS) attacks against
    Internet Explorer 7 via UTF-7 encoding.
  affected_package: python2x86
  vulnerable_versions:
  - 0.9.0
  - 0.9.1
  - '1.2'
  - '1.3'
  - 1.5.2
  - '1.6'
  - 1.6.1
  - 2.0.1
  - 2.1.1
  - 2.1.2
  - 2.1.3
  - 2.2.1
  - 2.2.2
  - 2.2.3
  - 2.3.1
  - 2.3.2
  - 2.3.3
  - 2.3.4
  - 2.3.5
  - 2.3.7
  - 2.4.1
  - 2.4.2
  - 2.4.3
  - 2.4.4
  - 2.4.6
  - 2.5.1
  - 2.5.2
  - 2.5.3
  - 2.5.4
  - 2.5.6
  - 2.6.1
  - 2.6.2
  - 2.6.3
  - 2.6.4
  - 2.6.5
  - 2.6.6
  - '2.7'
  - 2.7.1
  - 2.7.2
  package_manager: nuget
  cve:
  - CVE-2011-4940
  disclosed_date: 2012-06-27
  created_date: 2012-06-27
  last_modified_date: 2017-04-19
  credit:
  - OSSIndex
  references:
  - http://bugs.python.org/issue11442
  - http://jvn.jp/en/jp/JVN51176027/index.html
  - http://jvndb.jvn.jp/jvndb/JVNDB-2012-000063
  - http://secunia.com/advisories/50858
  - http://secunia.com/advisories/51024
  - http://secunia.com/advisories/51040
  - http://www.securityfocus.com/bid/54083
  - http://www.ubuntu.com/usn/USN-1592-1
  - http://www.ubuntu.com/usn/USN-1596-1
  - http://www.ubuntu.com/usn/USN-1613-1
  - http://www.ubuntu.com/usn/USN-1613-2
  - https://bugzilla.redhat.com/show_bug.cgi?id=803500
  source_url: https://ossindex.net/resource/package/8399917114/vulnerabilities
- id: ossindex:nuget:python2x86:348509
  title: "[CVE-2011-4944]  Permissions, Privileges, and Access Controls"
  description: Python 2.6 through 3.2 creates ~/.pypirc with world-readable permissions
    before changing them after data has been written, which introduces a race condition
    that allows local users to obtain a username and password by reading this file.
  affected_package: python2x86
  vulnerable_versions:
  - '2.6'
  - 2.6.1
  - 2.6.2
  - 2.6.2150
  - 2.6.3
  - 2.6.4
  - 2.6.5
  - 2.6.6
  - 2.6.6150
  - 2.6.7
  - 2.6.8
  - '2.7'
  - 2.7.1
  - 2.7.1150
  - 2.7.2
  - 2.7.2150
  - 2.7.3
  - '3.0'
  - 3.0.1
  - '3.1'
  - 3.1.1
  - 3.1.2
  - 3.1.2150
  - 3.1.3
  - 3.1.4
  - 3.1.5
  - '3.2'
  package_manager: nuget
  cve:
  - CVE-2011-4944
  disclosed_date: 2012-08-27
  created_date: 2012-08-27
  last_modified_date: 2017-04-19
  credit:
  - OSSIndex
  references:
  - http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=650555
  - http://bugs.python.org/file23824/pypirc-secure.diff
  - http://bugs.python.org/issue13512
  - http://lists.apple.com/archives/security-announce/2013/Oct/msg00004.html
  - http://secunia.com/advisories/50858
  - http://secunia.com/advisories/51024
  - http://secunia.com/advisories/51040
  - http://secunia.com/advisories/51087
  - http://secunia.com/advisories/51089
  - http://www.openwall.com/lists/oss-security/2012/03/27/10
  - http://www.openwall.com/lists/oss-security/2012/03/27/2
  - http://www.openwall.com/lists/oss-security/2012/03/27/5
  - http://www.ubuntu.com/usn/USN-1592-1
  - http://www.ubuntu.com/usn/USN-1596-1
  - http://www.ubuntu.com/usn/USN-1613-1
  - http://www.ubuntu.com/usn/USN-1613-2
  - http://www.ubuntu.com/usn/USN-1615-1
  - http://www.ubuntu.com/usn/USN-1616-1
  - https://bugzilla.redhat.com/show_bug.cgi?id=758905
  source_url: https://ossindex.net/resource/package/8399917114/vulnerabilities
- id: ossindex:nuget:python2x86:349600
  title: "[CVE-2012-0845]  Resource Management Errors"
  description: SimpleXMLRPCServer.py in SimpleXMLRPCServer in Python before 2.6.8,
    2.7.x before 2.7.3, 3.x before 3.1.5, and 3.2.x before 3.2.3 allows remote attackers
    to cause a denial of service (infinite loop and CPU consumption) via an XML-RPC
    POST request that contains a smaller amount of data than specified by the Content-Length
    header.
  affected_package: python2x86
  vulnerable_versions:
  - 0.9.0
  - 0.9.1
  - '1.2'
  - '1.3'
  - 1.5.2
  - '1.6'
  - 1.6.1
  - '2.0'
  - 2.0.1
  - '2.1'
  - 2.1.1
  - 2.1.2
  - 2.1.3
  - '2.2'
  - 2.2.1
  - 2.2.2
  - 2.2.3
  - '2.3'
  - 2.3.1
  - 2.3.2
  - 2.3.3
  - 2.3.4
  - 2.3.5
  - 2.3.7
  - '2.4'
  - 2.4.1
  - 2.4.2
  - 2.4.3
  - 2.4.4
  - 2.4.6
  - '2.5'
  - 2.5.1
  - 2.5.150
  - 2.5.2
  - 2.5.3
  - 2.5.4
  - 2.5.6
  - '2.6'
  - 2.6.1
  - 2.6.2
  - 2.6.2150
  - 2.6.3
  - 2.6.4
  - 2.6.5
  - 2.6.6
  - 2.6.6150
  - 2.6.7
  - '2.7'
  - 2.7.1
  - 2.7.1150
  - 2.7.2
  - 2.7.2150
  - '3.0'
  - 3.0.1
  - '3.1'
  - 3.1.1
  - 3.1.2
  - 3.1.3
  - 3.1.4
  - '3.2'
  - 3.2.2150
  package_manager: nuget
  cve:
  - CVE-2012-0845
  disclosed_date: 2012-10-05
  created_date: 2012-10-05
  last_modified_date: 2017-04-19
  credit:
  - OSSIndex
  references:
  - http://bugs.python.org/issue14001
  - http://lists.apple.com/archives/security-announce/2013/Oct/msg00004.html
  - http://python.org/download/releases/2.6.8/
  - http://python.org/download/releases/2.7.3/
  - http://python.org/download/releases/3.1.5/
  - http://python.org/download/releases/3.2.3/
  - http://secunia.com/advisories/50858
  - http://secunia.com/advisories/51024
  - http://secunia.com/advisories/51040
  - http://secunia.com/advisories/51087
  - http://secunia.com/advisories/51089
  - http://www.openwall.com/lists/oss-security/2012/02/13/4
  - http://www.securitytracker.com/id?1026689
  - http://www.ubuntu.com/usn/USN-1592-1
  - http://www.ubuntu.com/usn/USN-1596-1
  - http://www.ubuntu.com/usn/USN-1613-1
  - http://www.ubuntu.com/usn/USN-1613-2
  - http://www.ubuntu.com/usn/USN-1615-1
  - http://www.ubuntu.com/usn/USN-1616-1
  - https://bugzilla.redhat.com/show_bug.cgi?id=789790
  source_url: https://ossindex.net/resource/package/8399917114/vulnerabilities
- id: ossindex:nuget:python2x86:349857
  title: "[CVE-2012-1150]  Cryptographic Issues"
  description: Python before 2.6.8, 2.7.x before 2.7.3, 3.x before 3.1.5, and 3.2.x
    before 3.2.3 computes hash values without restricting the ability to trigger hash
    collisions predictably, which allows context-dependent attackers to cause a denial
    of service (CPU consumption) via crafted input to an application that maintains
    a hash table.
  affected_package: python2x86
  vulnerable_versions:
  - 0.9.0
  - 0.9.1
  - '1.2'
  - '1.3'
  - 1.5.2
  - '1.6'
  - 1.6.1
  - '2.0'
  - 2.0.1
  - '2.1'
  - 2.1.1
  - 2.1.2
  - 2.1.3
  - '2.2'
  - 2.2.1
  - 2.2.2
  - 2.2.3
  - '2.3'
  - 2.3.1
  - 2.3.2
  - 2.3.3
  - 2.3.4
  - 2.3.5
  - 2.3.7
  - '2.4'
  - 2.4.1
  - 2.4.2
  - 2.4.3
  - 2.4.4
  - 2.4.6
  - '2.5'
  - 2.5.1
  - 2.5.150
  - 2.5.2
  - 2.5.3
  - 2.5.4
  - 2.5.6
  - '2.6'
  - 2.6.1
  - 2.6.2
  - 2.6.2150
  - 2.6.3
  - 2.6.4
  - 2.6.5
  - 2.6.6
  - 2.6.6150
  - 2.6.7
  - '2.7'
  - 2.7.1
  - 2.7.1150
  - 2.7.2
  - 2.7.2150
  - '3.0'
  - 3.0.1
  - '3.1'
  - 3.1.1
  - 3.1.2
  - 3.1.3
  - 3.1.4
  - '3.2'
  - 3.2.2150
  package_manager: nuget
  cve:
  - CVE-2012-1150
  disclosed_date: 2012-10-05
  created_date: 2012-10-05
  last_modified_date: 2017-04-19
  credit:
  - OSSIndex
  references:
  - http://bugs.python.org/issue13703
  - http://lists.apple.com/archives/security-announce/2013/Oct/msg00004.html
  - http://mail.python.org/pipermail/python-dev/2011-December/115116.html
  - http://mail.python.org/pipermail/python-dev/2012-January/115892.html
  - http://python.org/download/releases/2.6.8/
  - http://python.org/download/releases/2.7.3/
  - http://python.org/download/releases/3.1.5/
  - http://python.org/download/releases/3.2.3/
  - http://secunia.com/advisories/50858
  - http://secunia.com/advisories/51087
  - http://secunia.com/advisories/51089
  - http://www.openwall.com/lists/oss-security/2012/03/10/3
  - http://www.ubuntu.com/usn/USN-1592-1
  - http://www.ubuntu.com/usn/USN-1596-1
  - http://www.ubuntu.com/usn/USN-1615-1
  - http://www.ubuntu.com/usn/USN-1616-1
  - https://bugzilla.redhat.com/show_bug.cgi?id=750555
  source_url: https://ossindex.net/resource/package/8399917114/vulnerabilities
- id: ossindex:nuget:python2x86:350670
  title: "[CVE-2012-2135] The utf-16 decoder in Python 3.1 through 3.3 does not update
    the aligned&#95;end var..."
  description: The utf-16 decoder in Python 3.1 through 3.3 does not update the aligned_end
    variable after calling the unicode_decode_call_errorhandler function, which allows
    remote attackers to obtain sensitive information (process memory) or cause a denial
    of service (memory corruption and crash) via unspecified vectors.
  affected_package: python2x86
  vulnerable_versions:
  - '3.1'
  - 3.1.1
  - 3.1.2
  - 3.1.5
  - '3.2'
  - 3.2.2150
  - 3.2.3
  - '3.3'
  package_manager: nuget
  cve:
  - CVE-2012-2135
  disclosed_date: 2012-08-14
  created_date: 2012-08-14
  last_modified_date: 2017-04-19
  credit:
  - OSSIndex
  references:
  - http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=670389
  - http://bugs.python.org/issue14579
  - http://secunia.com/advisories/51087
  - http://secunia.com/advisories/51089
  - http://www.openwall.com/lists/oss-security/2012/04/25/2
  - http://www.openwall.com/lists/oss-security/2012/04/25/4
  - http://www.ubuntu.com/usn/USN-1615-1
  - http://www.ubuntu.com/usn/USN-1616-1
  source_url: https://ossindex.net/resource/package/8399917114/vulnerabilities
- id: ossindex:nuget:python2x86:355780
  title: "[CVE-2013-2099]  Resource Management Errors"
  description: Algorithmic complexity vulnerability in the ssl.match_hostname function
    in Python 3.2.x, 3.3.x, and earlier, and unspecified versions of python-backports-ssl_match_hostname
    as used for older Python versions, allows remote attackers to cause a denial of
    service (CPU consumption) via multiple wildcard characters in the common name
    in a certificate.
  affected_package: python2x86
  vulnerable_versions:
  - 3.2.0
  - 3.2.1
  - 3.2.2
  - 3.2.3
  - 3.2.4
  - 3.2.5
  - 3.3.0
  - 3.3.1
  - 3.3.2
  package_manager: nuget
  cve:
  - CVE-2013-2099
  disclosed_date: 2013-10-09
  created_date: 2013-10-09
  last_modified_date: 2017-04-19
  credit:
  - OSSIndex
  references:
  - http://bugs.python.org/issue17980
  - http://rhn.redhat.com/errata/RHSA-2014-1690.html
  - http://secunia.com/advisories/55107
  - http://secunia.com/advisories/55116
  - http://www.openwall.com/lists/oss-security/2013/05/16/6
  - http://www.ubuntu.com/usn/USN-1983-1
  - http://www.ubuntu.com/usn/USN-1984-1
  - http://www.ubuntu.com/usn/USN-1985-1
  - https://access.redhat.com/errata/RHSA-2016:1166
  - https://bugzilla.redhat.com/show_bug.cgi?id=963260
  source_url: https://ossindex.net/resource/package/8399917114/vulnerabilities
- id: ossindex:nuget:python2x86:357451
  title: "[CVE-2013-4238]  Improper Input Validation"
  description: The ssl.match_hostname function in the SSL module in Python 2.6 through
    3.4 does not properly handle a '\0' character in a domain name in the Subject
    Alternative Name field of an X.509 certificate, which allows man-in-the-middle
    attackers to spoof arbitrary SSL servers via a crafted certificate issued by a
    legitimate Certification Authority, a related issue to CVE-2009-2408.
  affected_package: python2x86
  vulnerable_versions:
  - '2.6'
  - 2.6.1
  - 2.6.2
  - 2.6.2150
  - 2.6.3
  - 2.6.4
  - 2.6.5
  - 2.6.6
  - 2.6.6150
  - 2.6.7
  - 2.6.8
  - '2.7'
  - 2.7.1
  - 2.7.1150
  - 2.7.2
  - 2.7.2150
  - 2.7.3
  - '3.0'
  - 3.0.1
  - '3.1'
  - 3.1.1
  - 3.1.2
  - 3.1.2150
  - 3.1.3
  - 3.1.4
  - 3.1.5
  - '3.2'
  - 3.2.2150
  - 3.2.3
  - '3.3'
  - '3.4'
  package_manager: nuget
  cve:
  - CVE-2013-4238
  disclosed_date: 2013-08-18
  created_date: 2013-08-18
  last_modified_date: 2017-04-19
  credit:
  - OSSIndex
  references:
  - http://bugs.python.org/issue18709
  - http://lists.opensuse.org/opensuse-updates/2013-09/msg00026.html
  - http://lists.opensuse.org/opensuse-updates/2013-09/msg00027.html
  - http://lists.opensuse.org/opensuse-updates/2013-09/msg00028.html
  - http://lists.opensuse.org/opensuse-updates/2013-09/msg00029.html
  - http://lists.opensuse.org/opensuse-updates/2013-09/msg00042.html
  - http://lists.opensuse.org/opensuse-updates/2013-09/msg00043.html
  - http://rhn.redhat.com/errata/RHSA-2013-1582.html
  - http://seclists.org/fulldisclosure/2014/Dec/23
  - http://www.debian.org/security/2014/dsa-2880
  - http://www.securityfocus.com/archive/1/archive/1/534161/100/0/threaded
  - http://www.ubuntu.com/usn/USN-1982-1
  - http://www.vmware.com/security/advisories/VMSA-2014-0012.html
  - https://bugzilla.redhat.com/show_bug.cgi?id=996381
  source_url: https://ossindex.net/resource/package/8399917114/vulnerabilities
- id: ossindex:nuget:python2x86:359424
  title: "[CVE-2013-7040]  Cryptographic Issues"
  description: 'Python 2.7 before 3.4 only uses the last eight bits of the prefix
    to randomize hash values, which causes it to compute hash values without restricting
    the ability to trigger hash collisions predictably and makes it easier for context-dependent
    attackers to cause a denial of service (CPU consumption) via crafted input to
    an application that maintains a hash table.  NOTE: this vulnerability exists because
    of an incomplete fix for CVE-2012-1150.'
  affected_package: python2x86
  vulnerable_versions:
  - '2.7'
  - 2.7.1
  - 2.7.1150
  - 2.7.2
  - 2.7.2150
  - 2.7.3
  - 2.7.4
  - 2.7.5
  - 2.7.6
  - 2.7.7
  - '3.0'
  - 3.0.1
  - '3.1'
  - 3.1.1
  - 3.1.2
  - 3.1.3
  - 3.1.4
  - 3.1.5
  - '3.2'
  - 3.2.0
  - 3.2.1
  - 3.2.2
  - 3.2.2150
  - 3.2.3
  - 3.2.4
  - 3.2.5
  - '3.3'
  - 3.3.0
  - 3.3.1
  - 3.3.2
  - 3.3.3
  - 3.3.4
  - 3.3.5
  package_manager: nuget
  cve:
  - CVE-2013-7040
  disclosed_date: 2014-05-19
  created_date: 2014-05-19
  last_modified_date: 2017-04-19
  credit:
  - OSSIndex
  references:
  - http://bugs.python.org/issue14621
  - http://lists.apple.com/archives/security-announce/2015/Aug/msg00001.html
  - http://www.openwall.com/lists/oss-security/2013/12/09/13
  - http://www.openwall.com/lists/oss-security/2013/12/09/3
  - http://www.securityfocus.com/bid/64194
  - https://support.apple.com/kb/HT205031
  source_url: https://ossindex.net/resource/package/8399917114/vulnerabilities
- id: ossindex:nuget:python2x86:359616
  title: "[CVE-2013-7338]  Improper Input Validation"
  description: Python before 3.3.4 RC1 allows remote attackers to cause a denial of
    service (infinite loop and CPU consumption) via a file size value larger than
    the size of the zip file to the (1) ZipExtFile.read, (2) ZipExtFile.read(n), (3)
    ZipExtFile.readlines, (4) ZipFile.extract, or (5) ZipFile.extractall function.
  affected_package: python2x86
  vulnerable_versions:
  - '3.3'
  - 3.3.0
  - 3.3.1
  - 3.3.2
  - 3.3.3
  - 3.3.4
  package_manager: nuget
  cve:
  - CVE-2013-7338
  disclosed_date: 2014-04-22
  created_date: 2014-04-22
  last_modified_date: 2017-04-19
  credit:
  - OSSIndex
  references:
  - http://bugs.python.org/issue20078
  - http://hg.python.org/cpython/rev/79ea4ce431b1
  - http://lists.apple.com/archives/security-announce/2015/Aug/msg00001.html
  - http://lists.opensuse.org/opensuse-updates/2014-05/msg00008.html
  - http://seclists.org/oss-sec/2014/q1/592
  - http://seclists.org/oss-sec/2014/q1/595
  - http://www.securityfocus.com/bid/65179
  - http://www.securitytracker.com/id/1029973
  - https://docs.python.org/3.3/whatsnew/changelog.html
  - https://support.apple.com/kb/HT205031
  source_url: https://ossindex.net/resource/package/8399917114/vulnerabilities
- id: ossindex:nuget:python2x86:361158
  title: "[CVE-2014-1912]  Improper Restriction of Operations within the Bounds of
    a Memory Buffer"
  description: Buffer overflow in the socket.recvfrom_into function in Modules/socketmodule.c
    in Python 2.5 before 2.7.7, 3.x before 3.3.4, and 3.4.x before 3.4rc1 allows remote
    attackers to execute arbitrary code via a crafted string.
  affected_package: python2x86
  vulnerable_versions:
  - '2.5'
  - 2.5.1
  - 2.5.150
  - 2.5.2
  - 2.5.3
  - 2.5.4
  - 2.5.6
  - '2.6'
  - 2.6.1
  - 2.6.2
  - 2.6.2150
  - 2.6.3
  - 2.6.4
  - 2.6.5
  - 2.6.6
  - 2.6.6150
  - 2.6.7
  - 2.6.8
  - '2.7'
  - 2.7.1
  - 2.7.1150
  - 2.7.2
  - 2.7.2150
  - 2.7.3
  - 2.7.4
  - 2.7.5
  - 2.7.6
  - '3.0'
  - 3.0.1
  - '3.1'
  - 3.1.1
  - 3.1.2
  - 3.1.2150
  - 3.1.3
  - 3.1.4
  - 3.1.5
  - '3.2'
  - 3.2.0
  - 3.2.1
  - 3.2.2
  - 3.2.2150
  - 3.2.3
  - 3.2.4
  - 3.2.5
  - '3.3'
  - 3.3.0
  - 3.3.1
  - 3.3.2
  - 3.3.3
  - '3.4'
  package_manager: nuget
  cve:
  - CVE-2014-1912
  disclosed_date: 2014-03-01
  created_date: 2014-03-01
  last_modified_date: 2017-04-19
  credit:
  - OSSIndex
  references:
  - http://bugs.python.org/issue20246
  - http://hg.python.org/cpython/rev/87673659d8f7
  - http://lists.apple.com/archives/security-announce/2015/Aug/msg00001.html
  - http://lists.opensuse.org/opensuse-updates/2014-04/msg00035.html
  - http://lists.opensuse.org/opensuse-updates/2014-05/msg00008.html
  - http://pastebin.com/raw.php?i=GHXSmNEg
  - http://rhn.redhat.com/errata/RHSA-2015-1064.html
  - http://rhn.redhat.com/errata/RHSA-2015-1330.html
  - http://www.debian.org/security/2014/dsa-2880
  - http://www.exploit-db.com/exploits/31875
  - http://www.openwall.com/lists/oss-security/2014/02/12/16
  - http://www.oracle.com/technetwork/security-advisory/cpujul2017-3236622.html
  - http://www.oracle.com/technetwork/topics/security/linuxbulletinjan2016-2867209.html
  - http://www.securityfocus.com/bid/65379
  - http://www.securitytracker.com/id/1029831
  - http://www.ubuntu.com/usn/USN-2125-1
  - https://security.gentoo.org/glsa/201503-10
  - https://support.apple.com/kb/HT205031
  - https://www.trustedsec.com/february-2014/python-remote-code-execution-socket-recvfrom_into/
  source_url: https://ossindex.net/resource/package/8399917114/vulnerabilities
- id: ossindex:nuget:python2x86:361749
  title: '[CVE-2014-2667]  Concurrent Execution using Shared Resource with Improper
    Synchronization ("Race Condition")'
  description: Race condition in the _get_masked_mode function in Lib/os.py in Python
    3.2 through 3.5, when exist_ok is set to true and multiple threads are used, might
    allow local users to bypass intended file permissions by leveraging a separate
    application vulnerability before the umask has been set to the expected value.
  affected_package: python2x86
  vulnerable_versions:
  - 3.2.0
  - 3.2.1
  - 3.2.2
  - 3.2.3
  - 3.2.4
  - 3.2.5
  - 3.2.6
  - 3.3.0
  - 3.3.1
  - 3.3.2
  - 3.3.3
  - 3.3.4
  - 3.3.5
  - 3.3.6
  - 3.4.0
  - 3.4.1
  - 3.4.2
  package_manager: nuget
  cve:
  - CVE-2014-2667
  disclosed_date: 2014-11-16
  created_date: 2014-11-16
  last_modified_date: 2017-04-19
  credit:
  - OSSIndex
  references:
  - http://bugs.python.org/issue21082
  - http://lists.opensuse.org/opensuse-updates/2014-05/msg00007.html
  - http://lists.opensuse.org/opensuse-updates/2014-05/msg00008.html
  - http://www.openwall.com/lists/oss-security/2014/03/28/15
  - http://www.openwall.com/lists/oss-security/2014/03/29/5
  - http://www.openwall.com/lists/oss-security/2014/03/30/4
  source_url: https://ossindex.net/resource/package/8399917114/vulnerabilities
- id: ossindex:nuget:python2x86:365277
  title: "[CVE-2014-7185]  Numeric Errors"
  description: Integer overflow in bufferobject.c in Python before 2.7.8 allows context-dependent
    attackers to obtain sensitive information from process memory via a large size
    and offset in a "buffer" function.
  affected_package: python2x86
  vulnerable_versions:
  - '2.7'
  - 2.7.1
  - 2.7.1150
  - 2.7.2
  - 2.7.2150
  - 2.7.3
  - 2.7.4
  - 2.7.5
  - 2.7.6
  - 2.7.7
  package_manager: nuget
  cve:
  - CVE-2014-7185
  disclosed_date: 2014-10-08
  created_date: 2014-10-08
  last_modified_date: 2017-04-19
  credit:
  - OSSIndex
  references:
  - http://bugs.python.org/issue21831
  - http://lists.apple.com/archives/security-announce/2015/Aug/msg00001.html
  - http://lists.fedoraproject.org/pipermail/package-announce/2014-October/139663.html
  - http://lists.opensuse.org/opensuse-updates/2014-10/msg00016.html
  - http://rhn.redhat.com/errata/RHSA-2015-1064.html
  - http://rhn.redhat.com/errata/RHSA-2015-1330.html
  - http://www.openwall.com/lists/oss-security/2014/09/23/5
  - http://www.openwall.com/lists/oss-security/2014/09/25/47
  - http://www.oracle.com/technetwork/topics/security/linuxbulletinjan2016-2867209.html
  - http://www.oracle.com/technetwork/topics/security/linuxbulletinoct2015-2719645.html
  - http://www.securityfocus.com/bid/70089
  - http://xforce.iss.net/xforce/xfdb/96193
  - https://bugzilla.redhat.com/show_bug.cgi?id=1146026
  - https://exchange.xforce.ibmcloud.com/vulnerabilities/96193
  - https://security.gentoo.org/glsa/201503-10
  - https://support.apple.com/kb/HT205031
  source_url: https://ossindex.net/resource/package/8399917114/vulnerabilities
- id: ossindex:nuget:python2x86:7157225164
  title: "[CVE-2014-9365] The HTTP clients in the (1) httplib, (2) urllib, (3) urllib2,
    and (4) xmlrpclib ..."
  description: The HTTP clients in the (1) httplib, (2) urllib, (3) urllib2, and (4)
    xmlrpclib libraries in CPython (aka Python) 2.x before 2.7.9 and 3.x before 3.4.3,
    when accessing an HTTPS URL, do not (a) check the certificate against a trust
    store or verify that the server hostname matches a domain name in the subject's
    (b) Common Name or (c) subjectAltName field of the X.509 certificate, which allows
    man-in-the-middle attackers to spoof SSL servers via an arbitrary valid certificate.
  affected_package: python2x86
  vulnerable_versions:
  - '2.0'
  - 2.0.1
  - '2.1'
  - 2.1.1
  - 2.1.2
  - 2.1.3
  - '2.2'
  - 2.2.1
  - 2.2.2
  - 2.2.3
  - '2.3'
  - 2.3.1
  - 2.3.2
  - 2.3.3
  - 2.3.4
  - 2.3.5
  - 2.3.7
  - '2.4'
  - 2.4.1
  - 2.4.2
  - 2.4.3
  - 2.4.4
  - 2.4.6
  - '2.5'
  - 2.5.1
  - 2.5.150
  - 2.5.2
  - 2.5.3
  - 2.5.4
  - 2.5.6
  - '2.6'
  - 2.6.1
  - 2.6.2
  - 2.6.2150
  - 2.6.3
  - 2.6.4
  - 2.6.5
  - 2.6.6
  - 2.6.6150
  - 2.6.7
  - 2.6.8
  - '2.7'
  - 2.7.1
  - 2.7.1150
  - 2.7.2
  - 2.7.2150
  - 2.7.3
  - 2.7.4
  - 2.7.5
  - 2.7.6
  - 2.7.7
  - 2.7.8
  - '3.0'
  - 3.0.1
  - '3.1'
  - 3.1.1
  - 3.1.2
  - 3.1.2150
  - 3.1.3
  - 3.1.4
  - 3.1.5
  - '3.2'
  - 3.2.0
  - 3.2.1
  - 3.2.2
  - 3.2.2150
  - 3.2.3
  - 3.2.4
  - 3.2.5
  - 3.2.6
  - '3.3'
  - 3.3.0
  - 3.3.1
  - 3.3.2
  - 3.3.3
  - 3.3.4
  - 3.3.5
  - 3.3.6
  - '3.4'
  - 3.4.0
  - 3.4.1
  - 3.4.2
  package_manager: nuget
  cve:
  - CVE-2014-9365
  disclosed_date: 2014-12-12
  created_date: 2014-12-12
  last_modified_date: 2017-04-19
  credit:
  - OSSIndex
  references:
  - http://bugs.python.org/issue22417
  - http://lists.apple.com/archives/security-announce/2015/Aug/msg00001.html
  - http://www.openwall.com/lists/oss-security/2014/12/11/1
  - http://www.oracle.com/technetwork/topics/security/bulletinjan2015-2370101.html
  - http://www.oracle.com/technetwork/topics/security/bulletinoct2015-2511968.html
  - http://www.securityfocus.com/bid/71639
  - https://access.redhat.com/errata/RHSA-2016:1166
  - https://access.redhat.com/errata/RHSA-2017:1162
  - https://access.redhat.com/errata/RHSA-2017:1868
  - https://security.gentoo.org/glsa/201503-10
  - https://support.apple.com/kb/HT205031
  - https://www.python.org/dev/peps/pep-0476/
  - https://www.python.org/downloads/release/python-279/
  source_url: https://ossindex.net/resource/package/8399917114/vulnerabilities
- id: ossindex:nuget:python2x86:8388963774
  title: "[CVE-2015-5652] Untrusted search path vulnerability in python.exe in Python
    through 3.5.0 on Win..."
  description: 'Untrusted search path vulnerability in python.exe in Python through
    3.5.0 on Windows allows local users to gain privileges via a Trojan horse readline.pyd
    file in the current working directory.  NOTE: the vendor says "It was determined
    that this is a longtime behavior of Python that cannot really be altered at this
    point."'
  affected_package: python2x86
  vulnerable_versions:
  - 3.5.0
  package_manager: nuget
  cve:
  - CVE-2015-5652
  disclosed_date: 2015-10-06
  created_date: 2015-10-06
  last_modified_date: 2017-04-19
  credit:
  - OSSIndex
  references:
  - http://jvn.jp/en/jp/JVN49503705/995204/index.html
  - http://jvn.jp/en/jp/JVN49503705/index.html
  - http://jvndb.jvn.jp/jvndb/JVNDB-2015-000141
  - http://www.securityfocus.com/bid/76929
  - https://h20566.www2.hpe.com/portal/site/hpsc/public/kb/docDisplay?docId=emr_na-c05324755
  source_url: https://ossindex.net/resource/package/8399917114/vulnerabilities
- id: ossindex:nuget:python2x86:8397116265
  title: "[CVE-2016-1494]  Improper Input Validation"
  description: The verify function in the RSA package for Python (Python-RSA) before
    3.3 allows attackers to spoof signatures with a small public exponent via crafted
    signature padding, aka a BERserk attack.
  affected_package: python2x86
  vulnerable_versions:
  - 3.2.6
  package_manager: nuget
  cve:
  - CVE-2016-1494
  disclosed_date: 2016-01-13
  created_date: 2016-01-13
  last_modified_date: 2017-04-19
  credit:
  - OSSIndex
  references:
  - http://lists.fedoraproject.org/pipermail/package-announce/2016-January/175897.html
  - http://lists.fedoraproject.org/pipermail/package-announce/2016-January/175942.html
  - http://lists.opensuse.org/opensuse-updates/2016-01/msg00032.html
  - http://www.openwall.com/lists/oss-security/2016/01/05/1
  - http://www.openwall.com/lists/oss-security/2016/01/05/3
  - http://www.securityfocus.com/bid/79829
  - https://bitbucket.org/sybren/python-rsa/pull-requests/14/security-fix-bb06-attack-in-verify-by/diff
  - https://blog.filippo.io/bleichenbacher-06-signature-forgery-in-python-rsa/
  source_url: https://ossindex.net/resource/package/8399917114/vulnerabilities
- id: ossindex:nuget:python2x86:8399186699
  title: "[CVE-2013-7440]  Data Handling"
  description: The ssl.match_hostname function in CPython (aka Python) before 2.7.9
    and 3.x before 3.3.3 does not properly handle wildcards in hostnames, which might
    allow man-in-the-middle attackers to spoof servers via a crafted certificate.
  affected_package: python2x86
  vulnerable_versions:
  - 2.7.8
  - '3.0'
  - 3.0.1
  - '3.1'
  - 3.1.1
  - 3.1.2
  - 3.1.2150
  - 3.1.3
  - 3.1.4
  - 3.1.5
  - '3.2'
  - 3.2.0
  - 3.2.1
  - 3.2.2
  - 3.2.2150
  - 3.2.3
  - 3.2.4
  - 3.2.5
  - 3.2.6
  - '3.3'
  - 3.3.0
  - 3.3.1
  - 3.3.2
  package_manager: nuget
  cve:
  - CVE-2013-7440
  disclosed_date: 2016-06-07
  created_date: 2016-06-07
  last_modified_date: 2017-04-19
  credit:
  - OSSIndex
  references:
  - http://seclists.org/oss-sec/2015/q2/483
  - http://seclists.org/oss-sec/2015/q2/523
  - http://www.securityfocus.com/bid/74707
  - https://access.redhat.com/errata/RHSA-2016:1166
  - https://bugs.python.org/issue17997
  - https://bugzilla.redhat.com/show_bug.cgi?id=1224999
  - https://hg.python.org/cpython/rev/10d0edadbcdd
  source_url: https://ossindex.net/resource/package/8399917114/vulnerabilities
- id: ossindex:nuget:python2x86:8400134396
  title: "[CVE-2016-2183]  Information Exposure"
  description: The DES and Triple DES ciphers, as used in the TLS, SSH, and IPSec
    protocols and other protocols and products, have a birthday bound of approximately
    four billion blocks, which makes it easier for remote attackers to obtain cleartext
    data via a birthday attack against a long-duration encrypted session, as demonstrated
    by an HTTPS session using Triple DES in CBC mode, aka a "Sweet32" attack.
  affected_package: python2x86
  vulnerable_versions:
  - '2.7'
  - '3.3'
  - 3.4.0
  - '3.5'
  - '3.6'
  package_manager: nuget
  cve:
  - CVE-2016-2183
  disclosed_date: 2016-09-01
  created_date: 2016-09-01
  last_modified_date: 2017-05-10
  credit:
  - OSSIndex
  references:
  - http://kb.juniper.net/InfoCenter/index?page=content&id=JSA10759
  - http://lists.opensuse.org/opensuse-security-announce/2016-10/msg00013.html
  - http://rhn.redhat.com/errata/RHSA-2017-0336.html
  - http://rhn.redhat.com/errata/RHSA-2017-0337.html
  - http://rhn.redhat.com/errata/RHSA-2017-0338.html
  - http://rhn.redhat.com/errata/RHSA-2017-0462.html
  - http://www-01.ibm.com/support/docview.wss?uid=nas8N1021697
  - http://www-01.ibm.com/support/docview.wss?uid=swg21991482
  - http://www-01.ibm.com/support/docview.wss?uid=swg21995039
  - http://www.oracle.com/technetwork/security-advisory/cpujul2017-3236622.html
  - http://www.oracle.com/technetwork/security-advisory/cpuoct2016-2881722.html
  - http://www.oracle.com/technetwork/security-advisory/cpuoct2017-3236626.html
  - http://www.oracle.com/technetwork/topics/security/linuxbulletinoct2016-3090545.html
  - http://www.oracle.com/technetwork/topics/security/ovmbulletinoct2016-3090547.html
  - http://www.securityfocus.com/bid/92630
  - http://www.securityfocus.com/bid/92630/references
  - http://www.securityfocus.com/bid/95568
  - http://www.securitytracker.com/id/1036696
  - http://www.splunk.com/view/SP-CAAAPSV
  - http://www.splunk.com/view/SP-CAAAPUE
  - https://access.redhat.com/articles/2548661
  - https://access.redhat.com/errata/RHSA-2017:1216
  - https://access.redhat.com/errata/RHSA-2017:2708
  - https://access.redhat.com/errata/RHSA-2017:2709
  - https://access.redhat.com/errata/RHSA-2017:2710
  - https://access.redhat.com/errata/RHSA-2017:3113
  - https://access.redhat.com/errata/RHSA-2017:3114
  - https://access.redhat.com/errata/RHSA-2017:3239
  - https://access.redhat.com/errata/RHSA-2017:3240
  - https://access.redhat.com/security/cve/cve-2016-2183
  - https://blog.cryptographyengineering.com/2016/08/24/attack-of-week-64-bit-ciphers-in-tls/
  - https://bto.bluecoat.com/security-advisory/sa133
  - https://bugs.python.org/issue27850
  - https://bugzilla.redhat.com/show_bug.cgi?id=1369383
  - https://bugzilla.suse.com/show_bug.cgi?id=995359
  - https://community.qualys.com/thread/16555
  - https://github.com/ssllabs/ssllabs-scan/issues/387#issuecomment-242514633
  - https://h20566.www2.hpe.com/hpsc/doc/public/display?docLocale=en_US&docId=emr_na-hpesbgn03765en_us
  - https://h20566.www2.hpe.com/hpsc/doc/public/display?docLocale=en_US&docId=emr_na-hpesbux03725en_us
  - https://h20566.www2.hpe.com/portal/site/hpsc/public/kb/docDisplay?docId=emr_na-c05302448
  - https://h20566.www2.hpe.com/portal/site/hpsc/public/kb/docDisplay?docId=emr_na-c05309984
  - https://h20566.www2.hpe.com/portal/site/hpsc/public/kb/docDisplay?docId=emr_na-c05323116
  - https://h20566.www2.hpe.com/portal/site/hpsc/public/kb/docDisplay?docId=emr_na-c05349499
  - https://h20566.www2.hpe.com/portal/site/hpsc/public/kb/docDisplay?docId=emr_na-c05356388
  - https://h20566.www2.hpe.com/portal/site/hpsc/public/kb/docDisplay?docId=emr_na-c05369403
  - https://h20566.www2.hpe.com/portal/site/hpsc/public/kb/docDisplay?docId=emr_na-c05369415
  - https://h20566.www2.hpe.com/portal/site/hpsc/public/kb/docDisplay?docId=emr_na-c05385680
  - https://h20566.www2.hpe.com/portal/site/hpsc/public/kb/docDisplay?docId=emr_na-c05390722
  - https://h20566.www2.hpe.com/portal/site/hpsc/public/kb/docDisplay?docId=emr_na-c05390849
  - https://kb.pulsesecure.net/articles/Pulse_Security_Advisories/SA40312
  - https://kc.mcafee.com/corporate/index?page=content&id=SB10171
  - https://nakedsecurity.sophos.com/2016/08/25/anatomy-of-a-cryptographic-collision-the-sweet32-attack/
  - https://nodejs.org/en/blog/vulnerability/september-2016-security-releases/
  - https://quickview.cloudapps.cisco.com/quickview/bug/CSCvb05575
  - https://security-tracker.debian.org/tracker/CVE-2016-2183
  - https://security.gentoo.org/glsa/201612-16
  - https://security.gentoo.org/glsa/201701-65
  - https://security.gentoo.org/glsa/201707-01
  - https://security.netapp.com/advisory/ntap-20160915-0001/
  - https://security.netapp.com/advisory/ntap-20170119-0001/
  - https://sweet32.info/
  - https://twitter.com/symantec/status/768786631159603200
  - https://www.ietf.org/mail-archive/web/tls/current/msg04560.html
  - https://www.nccgroup.trust/us/about-us/newsroom-and-events/blog/2016/august/new-practical-attacks-on-64-bit-block-ciphers-3des-blowfish/
  - https://www.openssl.org/blog/blog/2016/08/24/sweet32/
  - https://www.sigsac.org/ccs/CCS2016/accepted-papers/
  - https://www.suse.com/security/cve/CVE-2016-2183.html
  - https://www.tenable.com/security/tns-2016-16
  - https://www.tenable.com/security/tns-2016-20
  - https://www.tenable.com/security/tns-2016-21
  - https://www.tenable.com/security/tns-2017-09
  - https://www.teskalabs.com/blog/teskalabs-bulletin-160826-seacat-sweet32-issue
  source_url: https://ossindex.net/resource/package/8399917114/vulnerabilities
- id: ossindex:nuget:python2x86:8400136572
  title: "[CVE-2016-0772]  Protection Mechanism Failure"
  description: The smtplib library in CPython (aka Python) before 2.7.12, 3.x before
    3.4.5, and 3.5.x before 3.5.2 does not return an error when StartTLS fails, which
    might allow man-in-the-middle attackers to bypass the TLS protections by leveraging
    a network position between the client and the registry to block the StartTLS command,
    aka a "StartTLS stripping attack."
  affected_package: python2x86
  vulnerable_versions:
  - 2.7.11
  - '3.0'
  - 3.0.1
  - 3.1.0
  - 3.1.1
  - 3.1.2
  - 3.1.3
  - 3.1.4
  - 3.1.5
  - 3.2.0
  - 3.2.1
  - 3.2.2
  - 3.2.3
  - 3.2.4
  - 3.2.5
  - 3.2.6
  - 3.3.0
  - 3.3.1
  - 3.3.2
  - 3.3.3
  - 3.3.4
  - 3.3.5
  - 3.3.6
  - 3.4.0
  - 3.4.1
  - 3.4.2
  - 3.4.3
  - 3.4.4
  - 3.5.0
  - 3.5.1
  package_manager: nuget
  cve:
  - CVE-2016-0772
  disclosed_date: 2016-09-02
  created_date: 2016-09-02
  last_modified_date: 2017-04-19
  credit:
  - OSSIndex
  references:
  - http://rhn.redhat.com/errata/RHSA-2016-1626.html
  - http://rhn.redhat.com/errata/RHSA-2016-1627.html
  - http://rhn.redhat.com/errata/RHSA-2016-1628.html
  - http://rhn.redhat.com/errata/RHSA-2016-1629.html
  - http://rhn.redhat.com/errata/RHSA-2016-1630.html
  - http://www.openwall.com/lists/oss-security/2016/06/14/9
  - http://www.securityfocus.com/bid/91225
  - http://www.splunk.com/view/SP-CAAAPSV
  - http://www.splunk.com/view/SP-CAAAPUE
  - https://bugzilla.redhat.com/show_bug.cgi?id=1303647
  - https://docs.python.org/3.4/whatsnew/changelog.html#python-3-4-5
  - https://docs.python.org/3.5/whatsnew/changelog.html#python-3-5-2
  - https://hg.python.org/cpython/raw-file/v2.7.12/Misc/NEWS
  - https://hg.python.org/cpython/rev/b3ce713fb9be
  - https://hg.python.org/cpython/rev/d590114c2394
  - https://security.gentoo.org/glsa/201701-18
  source_url: https://ossindex.net/resource/package/8399917114/vulnerabilities
- id: ossindex:nuget:python2x86:8400136578
  title: "[CVE-2016-5636]  Integer Overflow or Wraparound"
  description: Integer overflow in the get_data function in zipimport.c in CPython
    (aka Python) before 2.7.12, 3.x before 3.4.5, and 3.5.x before 3.5.2 allows remote
    attackers to have unspecified impact via a negative data size value, which triggers
    a heap-based buffer overflow.
  affected_package: python2x86
  vulnerable_versions:
  - 2.7.11
  - '3.0'
  - 3.0.1
  - 3.1.0
  - 3.1.1
  - 3.1.2
  - 3.1.3
  - 3.1.4
  - 3.1.5
  - 3.2.0
  - 3.2.1
  - 3.2.2
  - 3.2.3
  - 3.2.4
  - 3.2.5
  - 3.2.6
  - 3.3.0
  - 3.3.1
  - 3.3.2
  - 3.3.3
  - 3.3.4
  - 3.3.5
  - 3.3.6
  - 3.4.0
  - 3.4.1
  - 3.4.2
  - 3.4.3
  - 3.4.4
  - 3.5.0
  - 3.5.1
  package_manager: nuget
  cve:
  - CVE-2016-5636
  disclosed_date: 2016-09-02
  created_date: 2016-09-02
  last_modified_date: 2017-04-19
  credit:
  - OSSIndex
  references:
  - http://rhn.redhat.com/errata/RHSA-2016-2586.html
  - http://www.openwall.com/lists/oss-security/2016/06/15/15
  - http://www.openwall.com/lists/oss-security/2016/06/16/1
  - http://www.oracle.com/technetwork/topics/security/bulletinjul2016-3090568.html
  - http://www.securityfocus.com/bid/91247
  - http://www.securitytracker.com/id/1038138
  - http://www.splunk.com/view/SP-CAAAPSV
  - http://www.splunk.com/view/SP-CAAAPUE
  - https://bugs.python.org/issue26171
  - https://docs.python.org/3.4/whatsnew/changelog.html#python-3-4-5
  - https://docs.python.org/3.5/whatsnew/changelog.html#python-3-5-2
  - https://hg.python.org/cpython/raw-file/v2.7.12/Misc/NEWS
  - https://security.gentoo.org/glsa/201701-18
  source_url: https://ossindex.net/resource/package/8399917114/vulnerabilities
- id: ossindex:nuget:python2x86:8400136579
  title: '[CVE-2016-5699]  Improper Neutralization of CRLF Sequences in HTTP Headers
    ("HTTP Response Splitting")'
  description: CRLF injection vulnerability in the HTTPConnection.putheader function
    in urllib2 and urllib in CPython (aka Python) before 2.7.10 and 3.x before 3.4.4
    allows remote attackers to inject arbitrary HTTP headers via CRLF sequences in
    a URL.
  affected_package: python2x86
  vulnerable_versions:
  - 2.7.9
  - '3.0'
  - 3.0.1
  - 3.1.0
  - 3.1.1
  - 3.1.2
  - 3.1.3
  - 3.1.4
  - 3.1.5
  - 3.2.0
  - 3.2.1
  - 3.2.2
  - 3.2.3
  - 3.2.4
  - 3.2.5
  - 3.2.6
  - 3.3.0
  - 3.3.1
  - 3.3.2
  - 3.3.3
  - 3.3.4
  - 3.3.5
  - 3.3.6
  - 3.4.0
  - 3.4.1
  - 3.4.2
  - 3.4.3
  package_manager: nuget
  cve:
  - CVE-2016-5699
  disclosed_date: 2016-09-02
  created_date: 2016-09-02
  last_modified_date: 2017-04-19
  credit:
  - OSSIndex
  references:
  - http://blog.blindspotsecurity.com/2016/06/advisory-http-header-injection-in.html
  - http://rhn.redhat.com/errata/RHSA-2016-1626.html
  - http://rhn.redhat.com/errata/RHSA-2016-1627.html
  - http://rhn.redhat.com/errata/RHSA-2016-1628.html
  - http://rhn.redhat.com/errata/RHSA-2016-1629.html
  - http://rhn.redhat.com/errata/RHSA-2016-1630.html
  - http://www.openwall.com/lists/oss-security/2016/06/14/7
  - http://www.openwall.com/lists/oss-security/2016/06/15/12
  - http://www.openwall.com/lists/oss-security/2016/06/16/2
  - http://www.oracle.com/technetwork/topics/security/bulletinjul2016-3090568.html
  - http://www.securityfocus.com/bid/91226
  - http://www.splunk.com/view/SP-CAAAPSV
  - http://www.splunk.com/view/SP-CAAAPUE
  - https://docs.python.org/3.4/whatsnew/changelog.html#python-3-4-4
  - https://hg.python.org/cpython/raw-file/v2.7.10/Misc/NEWS
  - https://hg.python.org/cpython/rev/1c45047c5102
  - https://hg.python.org/cpython/rev/bf3e1c9b80e9
  source_url: https://ossindex.net/resource/package/8399917114/vulnerabilities
