---
- id: snykio:pypi:plone.app.portlets:40190
  title: Denial of Service (DoS)
  description: |+
    [`plone.app.portlets`][1] is a Plone integration for the basic
    plone.portlets package.

    traverser.py in Plone 2.1 through 4.1, 4.2.x through 4.2.5, and 4.3.x
    through 4.3.1 allows remote attackers with administrator privileges to
    cause a denial of service (infinite loop and resource consumption) via
    unspecified vectors related to \"retrieving information for certain
    resources.\"



    [1]: https://pypi.python.org/pypi/plone.app.portlets
    \nDenial of Service (DoS) describes a family of attacks, all aimed at
    making a system inaccessible to its intended and legitimate users.

    Unlike other vulnerabilities, DoS attacks usually do not aim at
    breaching security. Rather, they are focused on making websites and
    services unavailable to genuine users resulting in downtime.

    One popular Denial of Service vulnerability is DDoS (a Distributed
    Denial of Service), an attack that attempts to clog network pipes to the
    system by generating a large volume of traffic from many machines.

    When it comes to open source libraries, DoS vulnerabilities allow
    attackers to trigger such a crash or crippling of the service by using a
    flaw either in the application code or from the use of open source
    libraries.

    Two common types of DoS vulnerabilities:

    * High CPU/Memory Consumption- An attacker sending crafted requests that
      could cause the system to take a disproportionate amount of time to
      process. For example,
      [commons-fileupload:commons-fileupload](SNYK-JAVA-COMMONSFILEUPLOAD-30082).

    * Crash - An attacker sending crafted requests that could cause the
      system to crash. For Example, [npm `ws` package](npm:ws:20171108)

  affected_package: plone.app.portlets
  vulnerable_versions:
  - "< 2.4.5"
  severity: medium
  package_manager: pypi
  cve:
  - CVE-2013-4188
  cwe:
  - CWE-399
  disclosed_date: 2013-03-18
  created_date: 2013-03-18
  last_modified_date: 2013-03-18
  credit:
  - Plone Security Team
  references:
  - https://plone.org/security/hotfix/20130618/denial-of-service-attack-by-privileged-users
  - https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2013-4188
  source_url: https://snyk.io/vuln/SNYK-PYTHON-PLONEAPPPORTLETS-40190
