---
- id: snykio:pypi:plone.app.blob:2012-11-06
  title: Arbitrary BLOB Read Permissions
  description: |
    [`plone.app.blob`][1] is a ZODB blob support for Plone.

    at\_download.py in Plone before 4.2.3 and 4.3 before beta 1 allows
    remote attackers to read arbitrary BLOBs (Files and Images) stored on
    custom content types via a crafted URL.



    [1]: https://pypi.python.org/pypi/plone.app.blob
    \n[`plone.app.blob`][1] is a ZODB blob support for Plone.

    at\_download.py in Plone before 4.2.3 and 4.3 before beta 1 allows
    remote attackers to read arbitrary BLOBs (Files and Images) stored on
    custom content types via a crafted URL.



    [1]: https://pypi.python.org/pypi/plone.app.blob
    \n[`plone.app.blob`][1] is a ZODB blob support for Plone.

    at\_download.py in Plone before 4.2.3 and 4.3 before beta 1 allows
    remote attackers to read arbitrary BLOBs (Files and Images) stored on
    custom content types via a crafted URL.



    [1]: https://pypi.python.org/pypi/plone.app.blob
  affected_package: plone.app.blob
  vulnerable_versions:
  - "< 1.5.2"
  severity: medium
  package_manager: pypi
  cve:
  - CVE-2012-5501
  cwe:
  - CWE-264
  credit:
  - Alessandro SauzheR
  references:
  - https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2012-5501
  - http://www.openwall.com/lists/oss-security/2012/11/10/1
  source_url: https://snyk.io/vuln/SNYK-PYTHON-PLONEAPPBLOB-40138
