---
- id: snykio:pypi:pywbem:2013-12-09
  title: Man-in-the-Middle (MitM)
  description: |
    [`pywbem`][1] is a pywbem - A WBEM client PyWBEM 0.7 and earlier uses a
    separate connection to validate X.509 certificates, which allows
    man-in-the-middle attackers to spoof a peer via an arbitrary
    certificate.



    [1]: https://pypi.python.org/pypi/pywbem
    \n[`pywbem`][1] is a pywbem - A WBEM client PyWBEM 0.7 and earlier uses a
    separate connection to validate X.509 certificates, which allows
    man-in-the-middle attackers to spoof a peer via an arbitrary
    certificate.



    [1]: https://pypi.python.org/pypi/pywbem
  affected_package: pywbem
  vulnerable_versions:
  - "<= 0.7.0"
  severity: medium
  package_manager: pypi
  cve:
  - CVE-2013-6418
  cwe:
  - CWE-20
  credit:
  - Unknown
  references:
  - https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2013-6418
  - http://seclists.org/oss-sec/2013/q4/531
  - http://www.oracle.com/technetwork/topics/security/bulletinjan2016-2867206.html
  - https://bugzilla.redhat.com/show_bug.cgi?id=1039801
  source_url: https://snyk.io/vuln/SNYK-PYTHON-PYWBEM-40238
- id: snykio:pypi:pywbem:2013-12-17
  title: Man in the Middle (MitM)
  description: |
    [`pywbem`][1] is a pywbem - A WBEM client PyWBEM 0.7 and earlier does
    not verify that the server hostname matches a domain name in the
    subject\'s Common Name (CN) or subjectAltName field of the X.509
    certificate, which allows man-in-the-middle attackers to spoof SSL
    servers via an arbitrary valid certificate.



    [1]: https://pypi.python.org/pypi/pywbem
    \n[`pywbem`][1] is a pywbem - A WBEM client PyWBEM 0.7 and earlier does
    not verify that the server hostname matches a domain name in the
    subject\'s Common Name (CN) or subjectAltName field of the X.509
    certificate, which allows man-in-the-middle attackers to spoof SSL
    servers via an arbitrary valid certificate.



    [1]: https://pypi.python.org/pypi/pywbem
  affected_package: pywbem
  vulnerable_versions:
  - "<= 0.7.0"
  severity: medium
  package_manager: pypi
  cve:
  - CVE-2013-6444
  cwe:
  - CWE-20
  credit:
  - Unknown
  references:
  - https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2013-6444
  - http://seclists.org/oss-sec/2013/q4/524
  - http://www.oracle.com/technetwork/topics/security/bulletinjan2016-2952098.html
  - https://bugzilla.redhat.com/show_bug.cgi?id=1044246
  source_url: https://snyk.io/vuln/SNYK-PYTHON-PYWBEM-40239
