---
- id: snykio:pypi:requests-kerberos:2014-08-09
  title: Authentication Bypass
  description: |
    [`requests_kerberos`][1] is a Kerberos authentication handler for
    python-requests.

    Affected versions of this package are vulnerable to Authentication
    Bypass due to not authenticating server responses via the
    `handle_response()` function.



    [1]: https://pypi.python.org/pypi/requests_kerberos
    \n[`requests_kerberos`][1] is a Kerberos authentication handler for
    python-requests.

    Affected versions of this package are vulnerable to Authentication
    Bypass due to not authenticating server responses via the
    `handle_response()` function.



    [1]: https://pypi.python.org/pypi/requests_kerberos
    \n[`requests_kerberos`][1] is a Kerberos authentication handler for
    python-requests.

    Affected versions of this package are vulnerable to Authentication
    Bypass due to not authenticating server responses via the
    `handle_response()` function.



    [1]: https://pypi.python.org/pypi/requests_kerberos
  affected_package: requests-kerberos
  vulnerable_versions:
  - ">= 0.2 < 0.6"
  severity: medium
  package_manager: pypi
  cve:
  - CVE-2014-8650
  cwe:
  - CWE-287
  credit:
  - Michael Komitee
  references:
  - https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2014-8650
  - https://github.com/requests/requests-kerberos/issues/35
  - https://github.com/requests/requests-kerberos/pull/36
  - https://github.com/requests/requests-kerberos/commit/208bebb7008796a07be0204d9b5beaa55d2373ae
  source_url: https://snyk.io/vuln/SNYK-PYTHON-REQUESTSKERBEROS-40296
